version: "3.8"
services:
  database:
    container_name: choochoo_database
    image: postgis/postgis:16-3.4-alpine
    restart: unless-stopped
    environment:
      PGUSER: choochoo
      POSTGRES_USER: choochoo
      POSTGRES_PASSWORD: choochoo
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    build:
      context: ../
      dockerfile: docker/Dockerfile-backend
    container_name: choochoo_backend
    image: choochoo/backend:latest
    restart: unless-stopped
    environment:
      DATABASE_URL: ${BACKEND_DATABASE_URL}
      JWT_SECRET_KEY: ${BACKEND_JWT_SECRET_KEY}
    ports:
      - 8080:8080
    depends_on:
      database:
        condition: service_healthy
  frontend:
    build:
      context: ../frontend
      dockerfile: ../docker/Dockerfile-frontend
    container_name: choochoo_frontend
    image: choochoo/frontend:latest
    restart: unless-stopped
    environment:
      API_BASE_URL: ${FRONTEND_API_BASE_URL}
      GEOPS_API_KEY: ${FRONTEND_GEOPS_API_KEY}
    ports:
      - 3000:80
    depends_on:
      - backend
