FROM gradle:8.5.0-jdk21-alpine as builder
COPY --chown=gradle:gradle . /home/gradle/src
WORKDIR /home/gradle/src
RUN gradle build --no-daemon -x test

FROM openjdk:21

EXPOSE 8080

RUN mkdir /app

WORKDIR /app

COPY --from=builder /home/gradle/src/build/libs/*.jar /app/app.jar

ENTRYPOINT ["java", "-jar", "/app/app.jar"]
