INSERT INTO public.canton (code, name) VALUES ('AG', 'Aargau');
INSERT INTO public.canton (code, name) VALUES ('OW', 'Obwalden');
INSERT INTO public.canton (code, name) VALUES ('BL', 'Basel-Landschaft');
INSERT INTO public.canton (code, name) VALUES ('GR', 'Graubünden');
INSERT INTO public.canton (code, name) VALUES ('ZG', 'Zug');
INSERT INTO public.canton (code, name) VALUES ('AR', 'Appenzell Ausserrhoden');
INSERT INTO public.canton (code, name) VALUES ('ZH', 'Zürich');
INSERT INTO public.canton (code, name) VALUES ('BS', 'Basel-Stadt');
INSERT INTO public.canton (code, name) VALUES ('LU', 'Luzern');
INSERT INTO public.canton (code, name) VALUES ('SG', 'St. Gallen');
INSERT INTO public.canton (code, name) VALUES ('NE', 'Neuchâtel');
INSERT INTO public.canton (code, name) VALUES ('TG', 'Thurgau');
INSERT INTO public.canton (code, name) VALUES ('JU', 'Jura');
INSERT INTO public.canton (code, name) VALUES ('BE', 'Bern');
INSERT INTO public.canton (code, name) VALUES ('AI', 'Appenzell Innerrhoden');
INSERT INTO public.canton (code, name) VALUES ('VD', 'Vaud');
INSERT INTO public.canton (code, name) VALUES ('TI', 'Ticino');
INSERT INTO public.canton (code, name) VALUES ('GL', 'Glarus');
INSERT INTO public.canton (code, name) VALUES ('UR', 'Uri');
INSERT INTO public.canton (code, name) VALUES ('VS', 'Valais');
INSERT INTO public.canton (code, name) VALUES ('GE', 'Genève');
INSERT INTO public.canton (code, name) VALUES ('SZ', 'Schwyz');
INSERT INTO public.canton (code, name) VALUES ('FR', 'Fribourg');
INSERT INTO public.canton (code, name) VALUES ('SO', 'Solothurn');
INSERT INTO public.canton (code, name) VALUES ('SH', 'Schaffhausen');
INSERT INTO public.canton (code, name) VALUES ('NW', 'Nidwalden');
