INSERT INTO public.locality (id, name) VALUES (1, 'Uerkheim');
INSERT INTO public.locality (id, name) VALUES (2, 'Engelberg');
INSERT INTO public.locality (id, name) VALUES (3, 'Vordemwald');
INSERT INTO public.locality (id, name) VALUES (4, 'Ramlinsburg');
INSERT INTO public.locality (id, name) VALUES (5, 'Poschiavo');
INSERT INTO public.locality (id, name) VALUES (6, 'Münchenstein');
INSERT INTO public.locality (id, name) VALUES (7, 'Zug');
INSERT INTO public.locality (id, name) VALUES (8, 'Risch');
INSERT INTO public.locality (id, name) VALUES (9, 'Teufen (AR)');
INSERT INTO public.locality (id, name) VALUES (10, 'Thalwil');
INSERT INTO public.locality (id, name) VALUES (11, 'Domat/Ems');
INSERT INTO public.locality (id, name) VALUES (12, 'Allschwil');
INSERT INTO public.locality (id, name) VALUES (13, 'Basel');
INSERT INTO public.locality (id, name) VALUES (14, 'Greppen');
INSERT INTO public.locality (id, name) VALUES (15, 'Kirchberg (SG)');
INSERT INTO public.locality (id, name) VALUES (16, 'Berneck');
INSERT INTO public.locality (id, name) VALUES (17, 'Marbach (SG)');
INSERT INTO public.locality (id, name) VALUES (18, 'Boudry');
INSERT INTO public.locality (id, name) VALUES (19, 'Scuol');
INSERT INTO public.locality (id, name) VALUES (20, 'Bischofszell');
INSERT INTO public.locality (id, name) VALUES (21, 'Les Breuleux');
INSERT INTO public.locality (id, name) VALUES (22, 'Horgen');
INSERT INTO public.locality (id, name) VALUES (23, 'Illnau-Effretikon');
INSERT INTO public.locality (id, name) VALUES (24, 'Sauge');
INSERT INTO public.locality (id, name) VALUES (25, 'Bütschwil-Ganterschwil');
INSERT INTO public.locality (id, name) VALUES (26, 'Schwende-Rüte');
INSERT INTO public.locality (id, name) VALUES (27, 'Yverdon-les-Bains');
INSERT INTO public.locality (id, name) VALUES (28, 'Frauenfeld');
INSERT INTO public.locality (id, name) VALUES (29, 'Chur');
INSERT INTO public.locality (id, name) VALUES (30, 'Monteceneri');
INSERT INTO public.locality (id, name) VALUES (31, 'Cevio');
INSERT INTO public.locality (id, name) VALUES (32, 'Langenthal');
INSERT INTO public.locality (id, name) VALUES (33, 'Wildhaus-Alt St. Johann');
INSERT INTO public.locality (id, name) VALUES (34, 'Avenches');
INSERT INTO public.locality (id, name) VALUES (35, 'Neckertal');
INSERT INTO public.locality (id, name) VALUES (36, 'Milvignes');
INSERT INTO public.locality (id, name) VALUES (37, 'Albula/Alvra');
INSERT INTO public.locality (id, name) VALUES (38, 'Glarus Nord');
INSERT INTO public.locality (id, name) VALUES (39, 'Luzern');
INSERT INTO public.locality (id, name) VALUES (40, 'Blonay - Saint-Légier');
INSERT INTO public.locality (id, name) VALUES (41, 'Zofingen');
INSERT INTO public.locality (id, name) VALUES (42, 'Baden');
INSERT INTO public.locality (id, name) VALUES (43, 'Montreux');
INSERT INTO public.locality (id, name) VALUES (44, 'Seedorf (UR)');
INSERT INTO public.locality (id, name) VALUES (45, 'La Tène');
INSERT INTO public.locality (id, name) VALUES (46, 'Plateau de Diesse');
INSERT INTO public.locality (id, name) VALUES (47, 'Herzogenbuchsee');
INSERT INTO public.locality (id, name) VALUES (48, 'Rapperswil-Jona');
INSERT INTO public.locality (id, name) VALUES (49, 'Hindelbank');
INSERT INTO public.locality (id, name) VALUES (50, 'Mörel-Filet');
INSERT INTO public.locality (id, name) VALUES (51, 'Chavornay');
INSERT INTO public.locality (id, name) VALUES (52, 'Saignelégier');
INSERT INTO public.locality (id, name) VALUES (53, 'Brig-Glis');
INSERT INTO public.locality (id, name) VALUES (54, 'Nesslau');
INSERT INTO public.locality (id, name) VALUES (55, 'Aarau');
INSERT INTO public.locality (id, name) VALUES (56, 'Balgach');
INSERT INTO public.locality (id, name) VALUES (57, 'Zürich');
INSERT INTO public.locality (id, name) VALUES (58, 'Oberriet (SG)');
INSERT INTO public.locality (id, name) VALUES (59, 'Lancy');
INSERT INTO public.locality (id, name) VALUES (60, 'Speicher');
INSERT INTO public.locality (id, name) VALUES (61, 'Bonaduz');
INSERT INTO public.locality (id, name) VALUES (62, 'Les Ponts-de-Martel');
INSERT INTO public.locality (id, name) VALUES (63, 'Arth');
INSERT INTO public.locality (id, name) VALUES (64, 'Feusisberg');
INSERT INTO public.locality (id, name) VALUES (65, 'Biasca');
INSERT INTO public.locality (id, name) VALUES (66, 'Langnau im Emmental');
INSERT INTO public.locality (id, name) VALUES (67, 'Eggiwil');
INSERT INTO public.locality (id, name) VALUES (68, 'Röthenbach im Emmental');
INSERT INTO public.locality (id, name) VALUES (69, 'Spiez');
INSERT INTO public.locality (id, name) VALUES (70, 'Neyruz (FR)');
INSERT INTO public.locality (id, name) VALUES (71, 'Lyssach');
INSERT INTO public.locality (id, name) VALUES (72, 'Andermatt');
INSERT INTO public.locality (id, name) VALUES (73, 'Solothurn');
INSERT INTO public.locality (id, name) VALUES (74, 'Sisikon');
INSERT INTO public.locality (id, name) VALUES (75, 'Hasle bei Burgdorf');
INSERT INTO public.locality (id, name) VALUES (76, 'Rüdtligen-Alchenflüh');
INSERT INTO public.locality (id, name) VALUES (77, 'Gunzgen');
INSERT INTO public.locality (id, name) VALUES (78, 'Neuenhof');
INSERT INTO public.locality (id, name) VALUES (79, 'Wallisellen');
INSERT INTO public.locality (id, name) VALUES (80, 'Rorschacherberg');
INSERT INTO public.locality (id, name) VALUES (81, 'Gais');
INSERT INTO public.locality (id, name) VALUES (82, 'Muttenz');
INSERT INTO public.locality (id, name) VALUES (83, 'Laufen');
INSERT INTO public.locality (id, name) VALUES (84, 'Ingenbohl');
INSERT INTO public.locality (id, name) VALUES (85, 'Kaltbrunn');
INSERT INTO public.locality (id, name) VALUES (86, 'Killwangen');
INSERT INTO public.locality (id, name) VALUES (87, 'Lottstetten');
INSERT INTO public.locality (id, name) VALUES (88, 'Courtételle');
INSERT INTO public.locality (id, name) VALUES (89, 'Gelterkinden');
INSERT INTO public.locality (id, name) VALUES (90, 'Küssnacht (SZ)');
INSERT INTO public.locality (id, name) VALUES (91, 'Cornaux');
INSERT INTO public.locality (id, name) VALUES (92, 'Rheineck');
INSERT INTO public.locality (id, name) VALUES (93, 'Horn');
INSERT INTO public.locality (id, name) VALUES (94, 'Mörschwil');
INSERT INTO public.locality (id, name) VALUES (95, 'Niederweningen');
INSERT INTO public.locality (id, name) VALUES (96, 'Aarburg');
INSERT INTO public.locality (id, name) VALUES (97, 'Murgenthal');
INSERT INTO public.locality (id, name) VALUES (98, 'Herisau');
INSERT INTO public.locality (id, name) VALUES (99, 'Altendorf');
INSERT INTO public.locality (id, name) VALUES (100, 'Flawil');
INSERT INTO public.locality (id, name) VALUES (101, 'Schänis');
INSERT INTO public.locality (id, name) VALUES (102, 'Walchwil');
INSERT INTO public.locality (id, name) VALUES (103, 'Laufenburg West');
INSERT INTO public.locality (id, name) VALUES (104, 'Stein (AG)');
INSERT INTO public.locality (id, name) VALUES (105, 'St. Margrethen Landesgrenze');
INSERT INTO public.locality (id, name) VALUES (106, 'St. Margrethen');
INSERT INTO public.locality (id, name) VALUES (107, 'Regensdorf');
INSERT INTO public.locality (id, name) VALUES (108, 'Romanshorn');
INSERT INTO public.locality (id, name) VALUES (109, 'Spreitenbach');
INSERT INTO public.locality (id, name) VALUES (110, 'Kloten');
INSERT INTO public.locality (id, name) VALUES (111, 'Konstanz Grenze (Abzw)');
INSERT INTO public.locality (id, name) VALUES (112, 'Suhr');
INSERT INTO public.locality (id, name) VALUES (113, 'Gossau (SG)');
INSERT INTO public.locality (id, name) VALUES (114, 'Wohlen (AG)');
INSERT INTO public.locality (id, name) VALUES (115, 'Pino confine');
INSERT INTO public.locality (id, name) VALUES (116, 'Kesswil');
INSERT INTO public.locality (id, name) VALUES (117, 'Mettmenstetten');
INSERT INTO public.locality (id, name) VALUES (118, 'Birmensdorf (ZH)');
INSERT INTO public.locality (id, name) VALUES (119, 'Oberrüti');
INSERT INTO public.locality (id, name) VALUES (120, 'Mühlau');
INSERT INTO public.locality (id, name) VALUES (121, 'Rothenthurm');
INSERT INTO public.locality (id, name) VALUES (122, 'Sattel');
INSERT INTO public.locality (id, name) VALUES (123, 'Steinen');
INSERT INTO public.locality (id, name) VALUES (124, 'Tramelan');
INSERT INTO public.locality (id, name) VALUES (125, 'Kallnach');
INSERT INTO public.locality (id, name) VALUES (126, 'Romont (FR)');
INSERT INTO public.locality (id, name) VALUES (127, 'Seeberg');
INSERT INTO public.locality (id, name) VALUES (128, 'Wil (SG)');
INSERT INTO public.locality (id, name) VALUES (129, 'Ersigen');
INSERT INTO public.locality (id, name) VALUES (130, 'Martigny');
INSERT INTO public.locality (id, name) VALUES (131, 'Sirnach');
INSERT INTO public.locality (id, name) VALUES (132, 'Aadorf');
INSERT INTO public.locality (id, name) VALUES (133, 'Fraubrunnen');
INSERT INTO public.locality (id, name) VALUES (134, 'Wattwil');
INSERT INTO public.locality (id, name) VALUES (135, 'Le Locle');
INSERT INTO public.locality (id, name) VALUES (136, 'Ilanz/Glion');
INSERT INTO public.locality (id, name) VALUES (137, 'Triengen');
INSERT INTO public.locality (id, name) VALUES (138, 'Belp');
INSERT INTO public.locality (id, name) VALUES (139, 'Davos');
INSERT INTO public.locality (id, name) VALUES (140, 'Lantsch/Lenz');
INSERT INTO public.locality (id, name) VALUES (141, 'Le Noirmont');
INSERT INTO public.locality (id, name) VALUES (142, 'Mühleberg');
INSERT INTO public.locality (id, name) VALUES (143, 'Zweisimmen');
INSERT INTO public.locality (id, name) VALUES (144, 'Bern');
INSERT INTO public.locality (id, name) VALUES (145, 'Muri bei Bern');
INSERT INTO public.locality (id, name) VALUES (146, 'Saanen');
INSERT INTO public.locality (id, name) VALUES (147, 'Vouvry');
INSERT INTO public.locality (id, name) VALUES (148, 'Crémines');
INSERT INTO public.locality (id, name) VALUES (149, 'Balsthal');
INSERT INTO public.locality (id, name) VALUES (150, 'Pollegio');
INSERT INTO public.locality (id, name) VALUES (151, 'Trub');
INSERT INTO public.locality (id, name) VALUES (152, 'Bellinzona');
INSERT INTO public.locality (id, name) VALUES (153, 'Lauterbrunnen');
INSERT INTO public.locality (id, name) VALUES (154, 'Ermatingen');
INSERT INTO public.locality (id, name) VALUES (155, 'Bremgarten (AG)');
INSERT INTO public.locality (id, name) VALUES (156, 'Jegenstorf');
INSERT INTO public.locality (id, name) VALUES (157, 'Glarus Süd');
INSERT INTO public.locality (id, name) VALUES (158, 'Ebnat-Kappel');
INSERT INTO public.locality (id, name) VALUES (159, 'Murten');
INSERT INTO public.locality (id, name) VALUES (160, 'Faido');
INSERT INTO public.locality (id, name) VALUES (161, 'Willisau');
INSERT INTO public.locality (id, name) VALUES (162, 'Chiasso');
INSERT INTO public.locality (id, name) VALUES (163, 'Trun');
INSERT INTO public.locality (id, name) VALUES (164, 'Steg-Hohtenn');
INSERT INTO public.locality (id, name) VALUES (165, 'Bas-Intyamon');
INSERT INTO public.locality (id, name) VALUES (166, 'Madiswil');
INSERT INTO public.locality (id, name) VALUES (167, 'Kemmental');
INSERT INTO public.locality (id, name) VALUES (168, 'Mendrisio');
INSERT INTO public.locality (id, name) VALUES (169, 'Heimenhausen');
INSERT INTO public.locality (id, name) VALUES (170, 'Arosa');
INSERT INTO public.locality (id, name) VALUES (171, 'Schaffhausen');
INSERT INTO public.locality (id, name) VALUES (172, 'Terre di Pedemonte');
INSERT INTO public.locality (id, name) VALUES (173, 'Schattdorf');
INSERT INTO public.locality (id, name) VALUES (174, 'Sulgen');
INSERT INTO public.locality (id, name) VALUES (175, 'Visp');
INSERT INTO public.locality (id, name) VALUES (176, 'Centovalli');
INSERT INTO public.locality (id, name) VALUES (177, 'Wichtrach');
INSERT INTO public.locality (id, name) VALUES (178, 'Zernez');
INSERT INTO public.locality (id, name) VALUES (179, 'Bourg-en-Lavaux');
INSERT INTO public.locality (id, name) VALUES (180, 'Romainmôtier-Envy');
INSERT INTO public.locality (id, name) VALUES (181, 'Wädenswil');
INSERT INTO public.locality (id, name) VALUES (182, 'Breil/Brigels');
INSERT INTO public.locality (id, name) VALUES (183, 'Tobel-Tägerschen');
INSERT INTO public.locality (id, name) VALUES (184, 'Safiental');
INSERT INTO public.locality (id, name) VALUES (185, 'Gachnang');
INSERT INTO public.locality (id, name) VALUES (186, 'Montfaucon');
INSERT INTO public.locality (id, name) VALUES (187, 'Münchwilen (TG)');
INSERT INTO public.locality (id, name) VALUES (188, 'Escholzmatt-Marbach');
INSERT INTO public.locality (id, name) VALUES (189, 'Eiken');
INSERT INTO public.locality (id, name) VALUES (190, 'Eppenberg-Wöschnau');
INSERT INTO public.locality (id, name) VALUES (191, 'Wassen');
INSERT INTO public.locality (id, name) VALUES (192, 'Matran');
INSERT INTO public.locality (id, name) VALUES (193, 'Bodio');
INSERT INTO public.locality (id, name) VALUES (194, 'Olten');
INSERT INTO public.locality (id, name) VALUES (195, 'Oberbipp');
INSERT INTO public.locality (id, name) VALUES (196, 'Göschenen');
INSERT INTO public.locality (id, name) VALUES (197, 'Bitsch');
INSERT INTO public.locality (id, name) VALUES (198, 'Saint-Saphorin (Lavaux)');
INSERT INTO public.locality (id, name) VALUES (199, 'Rivaz');
INSERT INTO public.locality (id, name) VALUES (200, 'Windisch');
INSERT INTO public.locality (id, name) VALUES (201, 'Uster');
INSERT INTO public.locality (id, name) VALUES (202, 'Realp');
INSERT INTO public.locality (id, name) VALUES (203, 'Corcelles-près-Payerne');
INSERT INTO public.locality (id, name) VALUES (204, 'Holderbank (AG)');
INSERT INTO public.locality (id, name) VALUES (205, 'Ecublens (VD)');
INSERT INTO public.locality (id, name) VALUES (206, 'Roche (VD)');
INSERT INTO public.locality (id, name) VALUES (207, 'Chardonne');
INSERT INTO public.locality (id, name) VALUES (208, 'Flüelen');
INSERT INTO public.locality (id, name) VALUES (209, 'Corgémont');
INSERT INTO public.locality (id, name) VALUES (210, 'Trimbach');
INSERT INTO public.locality (id, name) VALUES (211, 'Eschenz');
INSERT INTO public.locality (id, name) VALUES (212, 'Bussigny');
INSERT INTO public.locality (id, name) VALUES (213, 'Frick');
INSERT INTO public.locality (id, name) VALUES (214, 'Aigle');
INSERT INTO public.locality (id, name) VALUES (215, 'Hospental');
INSERT INTO public.locality (id, name) VALUES (216, 'Rougemont');
INSERT INTO public.locality (id, name) VALUES (217, 'Morges');
INSERT INTO public.locality (id, name) VALUES (218, 'L''Isle');
INSERT INTO public.locality (id, name) VALUES (219, 'Niedergösgen');
INSERT INTO public.locality (id, name) VALUES (220, 'Grengiols');
INSERT INTO public.locality (id, name) VALUES (221, 'Ormont-Dessus');
INSERT INTO public.locality (id, name) VALUES (222, 'Zermatt');
INSERT INTO public.locality (id, name) VALUES (223, 'Moutier');
INSERT INTO public.locality (id, name) VALUES (224, 'Hauenstein-Ifenthal');
INSERT INTO public.locality (id, name) VALUES (225, 'Wimmis');
INSERT INTO public.locality (id, name) VALUES (226, 'Bedretto');
INSERT INTO public.locality (id, name) VALUES (227, 'Wiler bei Utzenstorf');
INSERT INTO public.locality (id, name) VALUES (228, 'Roggwil (BE)');
INSERT INTO public.locality (id, name) VALUES (229, 'Attiswil');
INSERT INTO public.locality (id, name) VALUES (230, 'Tujetsch');
INSERT INTO public.locality (id, name) VALUES (231, 'Raron');
INSERT INTO public.locality (id, name) VALUES (232, 'Rupperswil');
INSERT INTO public.locality (id, name) VALUES (233, 'Bever');
INSERT INTO public.locality (id, name) VALUES (234, 'Deitingen');
INSERT INTO public.locality (id, name) VALUES (235, 'Egerkingen');
INSERT INTO public.locality (id, name) VALUES (236, 'Iseltwald');
INSERT INTO public.locality (id, name) VALUES (237, 'Quinto');
INSERT INTO public.locality (id, name) VALUES (238, 'Saint-Imier');
INSERT INTO public.locality (id, name) VALUES (239, 'Brienz (BE)');
INSERT INTO public.locality (id, name) VALUES (240, 'Gurtnellen');
INSERT INTO public.locality (id, name) VALUES (241, 'Bex');
INSERT INTO public.locality (id, name) VALUES (242, 'Pontresina');
INSERT INTO public.locality (id, name) VALUES (243, 'Ausserberg');
INSERT INTO public.locality (id, name) VALUES (244, 'Thunstetten');
INSERT INTO public.locality (id, name) VALUES (245, 'Kandergrund');
INSERT INTO public.locality (id, name) VALUES (246, 'Subingen');
INSERT INTO public.locality (id, name) VALUES (247, 'Däniken');
INSERT INTO public.locality (id, name) VALUES (248, 'Pully');
INSERT INTO public.locality (id, name) VALUES (249, 'Kreuzlingen');
INSERT INTO public.locality (id, name) VALUES (250, 'St. Niklaus');
INSERT INTO public.locality (id, name) VALUES (251, 'Wangen bei Olten');
INSERT INTO public.locality (id, name) VALUES (252, 'Dulliken');
INSERT INTO public.locality (id, name) VALUES (253, 'Därstetten');
INSERT INTO public.locality (id, name) VALUES (254, 'Chavannes-près-Renens');
INSERT INTO public.locality (id, name) VALUES (255, 'Lutry');
INSERT INTO public.locality (id, name) VALUES (256, 'Denges');
INSERT INTO public.locality (id, name) VALUES (257, 'Founex');
INSERT INTO public.locality (id, name) VALUES (258, 'Reichenbach im Kandertal');
INSERT INTO public.locality (id, name) VALUES (259, 'Baltschieder');
INSERT INTO public.locality (id, name) VALUES (260, 'Ollon');
INSERT INTO public.locality (id, name) VALUES (261, 'Corseaux');
INSERT INTO public.locality (id, name) VALUES (262, 'Bolken');
INSERT INTO public.locality (id, name) VALUES (263, 'Derendingen');
INSERT INTO public.locality (id, name) VALUES (264, 'Le Lieu');
INSERT INTO public.locality (id, name) VALUES (265, 'Bannwil');
INSERT INTO public.locality (id, name) VALUES (266, 'Frutigen');
INSERT INTO public.locality (id, name) VALUES (267, 'Glattfelden');
INSERT INTO public.locality (id, name) VALUES (268, 'St. Gallen');
INSERT INTO public.locality (id, name) VALUES (269, 'Eglisau');
INSERT INTO public.locality (id, name) VALUES (270, 'Koblenz');
INSERT INTO public.locality (id, name) VALUES (271, 'Sumvitg');
INSERT INTO public.locality (id, name) VALUES (272, 'Waldenburg');
INSERT INTO public.locality (id, name) VALUES (273, 'Stalden (VS)');
INSERT INTO public.locality (id, name) VALUES (274, 'Le Chenit');
INSERT INTO public.locality (id, name) VALUES (275, 'Rafz');
INSERT INTO public.locality (id, name) VALUES (276, 'Lalden');
INSERT INTO public.locality (id, name) VALUES (277, 'Epalinges');
INSERT INTO public.locality (id, name) VALUES (278, 'La Chaux-de-Fonds');
INSERT INTO public.locality (id, name) VALUES (279, 'Feuerthalen');
INSERT INTO public.locality (id, name) VALUES (280, 'Dallenwil');
INSERT INTO public.locality (id, name) VALUES (281, 'Baulmes');
INSERT INTO public.locality (id, name) VALUES (282, 'Rickenbach (ZH)');
INSERT INTO public.locality (id, name) VALUES (283, 'Winterthur');
INSERT INTO public.locality (id, name) VALUES (284, 'Embd');
INSERT INTO public.locality (id, name) VALUES (285, 'Saint-Léonard');
INSERT INTO public.locality (id, name) VALUES (286, 'Hausen (AG)');
INSERT INTO public.locality (id, name) VALUES (287, 'Oftringen');
INSERT INTO public.locality (id, name) VALUES (288, 'Ettingen');
INSERT INTO public.locality (id, name) VALUES (289, 'Ergisch');
INSERT INTO public.locality (id, name) VALUES (290, 'Marthalen');
INSERT INTO public.locality (id, name) VALUES (291, 'Hochdorf');
INSERT INTO public.locality (id, name) VALUES (292, 'Brusio');
INSERT INTO public.locality (id, name) VALUES (293, 'Villnachern');
INSERT INTO public.locality (id, name) VALUES (294, 'Hinwil');
INSERT INTO public.locality (id, name) VALUES (295, 'Sainte-Croix');
INSERT INTO public.locality (id, name) VALUES (296, 'Annemasse SBB');
INSERT INTO public.locality (id, name) VALUES (297, 'Salvan');
INSERT INTO public.locality (id, name) VALUES (298, 'Huttwil');
INSERT INTO public.locality (id, name) VALUES (299, 'Bissone');
INSERT INTO public.locality (id, name) VALUES (300, 'Biel/Bienne');
INSERT INTO public.locality (id, name) VALUES (301, 'Burgdorf');
INSERT INTO public.locality (id, name) VALUES (302, 'Arbedo-Castione');
INSERT INTO public.locality (id, name) VALUES (303, 'Locarno');
INSERT INTO public.locality (id, name) VALUES (304, 'Konolfingen');
INSERT INTO public.locality (id, name) VALUES (305, 'Kehrsatz');
INSERT INTO public.locality (id, name) VALUES (306, 'Sigriswil');
INSERT INTO public.locality (id, name) VALUES (307, 'Kerzers');
INSERT INTO public.locality (id, name) VALUES (308, 'Heimberg');
INSERT INTO public.locality (id, name) VALUES (309, 'Affoltern im Emmental');
INSERT INTO public.locality (id, name) VALUES (310, 'Wangen an der Aare');
INSERT INTO public.locality (id, name) VALUES (311, 'Vuadens');
INSERT INTO public.locality (id, name) VALUES (312, 'Meiringen');
INSERT INTO public.locality (id, name) VALUES (313, 'Bargen (BE)');
INSERT INTO public.locality (id, name) VALUES (314, 'Busswil bei Melchnau');
INSERT INTO public.locality (id, name) VALUES (315, 'Kirchberg (BE)');
INSERT INTO public.locality (id, name) VALUES (316, 'Zäziwil');
INSERT INTO public.locality (id, name) VALUES (317, 'Bleienbach');
INSERT INTO public.locality (id, name) VALUES (318, 'St. Stephan');
INSERT INTO public.locality (id, name) VALUES (319, 'Etziken');
INSERT INTO public.locality (id, name) VALUES (320, 'Köniz');
INSERT INTO public.locality (id, name) VALUES (321, 'Sumiswald');
INSERT INTO public.locality (id, name) VALUES (322, 'Broc');
INSERT INTO public.locality (id, name) VALUES (323, 'Sant''Antonino');
INSERT INTO public.locality (id, name) VALUES (324, 'Valeyres-sous-Montagny');
INSERT INTO public.locality (id, name) VALUES (325, 'Hedingen');
INSERT INTO public.locality (id, name) VALUES (326, 'Täsch');
INSERT INTO public.locality (id, name) VALUES (327, 'Leysin');
INSERT INTO public.locality (id, name) VALUES (328, 'La Tour-de-Peilz');
INSERT INTO public.locality (id, name) VALUES (329, 'Wald (ZH)');
INSERT INTO public.locality (id, name) VALUES (330, 'Strengelbach');
INSERT INTO public.locality (id, name) VALUES (331, 'Payerne');
INSERT INTO public.locality (id, name) VALUES (332, 'Tägerwilen');
INSERT INTO public.locality (id, name) VALUES (333, 'Buchs (SG)');
INSERT INTO public.locality (id, name) VALUES (334, 'Dietikon');
INSERT INTO public.locality (id, name) VALUES (335, 'Puidoux');
INSERT INTO public.locality (id, name) VALUES (336, 'Münchwilen (AG)');
INSERT INTO public.locality (id, name) VALUES (337, 'Otelfingen');
INSERT INTO public.locality (id, name) VALUES (338, 'Ballwil');
INSERT INTO public.locality (id, name) VALUES (339, 'Gaiserwald');
INSERT INTO public.locality (id, name) VALUES (340, 'Sarnen');
INSERT INTO public.locality (id, name) VALUES (341, 'Ballens');
INSERT INTO public.locality (id, name) VALUES (342, 'Pfaffnau');
INSERT INTO public.locality (id, name) VALUES (343, 'Lonay');
INSERT INTO public.locality (id, name) VALUES (344, 'Kaisten');
INSERT INTO public.locality (id, name) VALUES (345, 'Schwarzenburg');
INSERT INTO public.locality (id, name) VALUES (346, 'Bussnang');
INSERT INTO public.locality (id, name) VALUES (347, 'Merenschwand');
INSERT INTO public.locality (id, name) VALUES (348, 'Arbon');
INSERT INTO public.locality (id, name) VALUES (349, 'Lyss');
INSERT INTO public.locality (id, name) VALUES (350, 'Sierre');
INSERT INTO public.locality (id, name) VALUES (351, 'Montilliez');
INSERT INTO public.locality (id, name) VALUES (352, 'Drei Höfe');
INSERT INTO public.locality (id, name) VALUES (353, 'Leuk');
INSERT INTO public.locality (id, name) VALUES (354, 'La Grande Béroche');
INSERT INTO public.locality (id, name) VALUES (355, 'Goms');
INSERT INTO public.locality (id, name) VALUES (356, 'Re');
INSERT INTO public.locality (id, name) VALUES (357, 'Berg (TG)');
INSERT INTO public.locality (id, name) VALUES (358, 'Trimmis');
INSERT INTO public.locality (id, name) VALUES (359, 'Rebstein');
INSERT INTO public.locality (id, name) VALUES (360, 'Rickenbach (TG)');
INSERT INTO public.locality (id, name) VALUES (361, 'Pratteln');
INSERT INTO public.locality (id, name) VALUES (362, 'Egnach');
INSERT INTO public.locality (id, name) VALUES (363, 'Grabs');
INSERT INTO public.locality (id, name) VALUES (364, 'Les Bois');
INSERT INTO public.locality (id, name) VALUES (365, 'Sutz-Lattrigen');
INSERT INTO public.locality (id, name) VALUES (366, 'Rodersdorf');
INSERT INTO public.locality (id, name) VALUES (367, 'Grindelwald');
INSERT INTO public.locality (id, name) VALUES (368, 'Aarberg');
INSERT INTO public.locality (id, name) VALUES (369, 'Ferenbalm');
INSERT INTO public.locality (id, name) VALUES (370, 'Uetendorf');
INSERT INTO public.locality (id, name) VALUES (371, 'Zollikofen');
INSERT INTO public.locality (id, name) VALUES (372, 'Gampelen');
INSERT INTO public.locality (id, name) VALUES (373, 'Moosseedorf');
INSERT INTO public.locality (id, name) VALUES (374, 'Oberried am Brienzersee');
INSERT INTO public.locality (id, name) VALUES (375, 'Cressier (FR)');
INSERT INTO public.locality (id, name) VALUES (376, 'Lützelflüh');
INSERT INTO public.locality (id, name) VALUES (377, 'Seelisberg');
INSERT INTO public.locality (id, name) VALUES (378, 'Büren an der Aare');
INSERT INTO public.locality (id, name) VALUES (379, 'Turbenthal');
INSERT INTO public.locality (id, name) VALUES (380, 'Root');
INSERT INTO public.locality (id, name) VALUES (381, 'Mellingen');
INSERT INTO public.locality (id, name) VALUES (382, 'Mägenwil');
INSERT INTO public.locality (id, name) VALUES (383, 'Eschenbach (LU)');
INSERT INTO public.locality (id, name) VALUES (384, 'Jestetten Süd');
INSERT INTO public.locality (id, name) VALUES (385, 'Goldach');
INSERT INTO public.locality (id, name) VALUES (386, 'Oberrohrdorf');
INSERT INTO public.locality (id, name) VALUES (387, 'Delémont');
INSERT INTO public.locality (id, name) VALUES (388, 'Rothenbrunnen');
INSERT INTO public.locality (id, name) VALUES (389, 'Salgesch');
INSERT INTO public.locality (id, name) VALUES (390, 'Quarten');
INSERT INTO public.locality (id, name) VALUES (391, 'Neuhausen am Rheinfall');
INSERT INTO public.locality (id, name) VALUES (392, 'Wartau');
INSERT INTO public.locality (id, name) VALUES (393, 'Daillens');
INSERT INTO public.locality (id, name) VALUES (394, 'Bellevue');
INSERT INTO public.locality (id, name) VALUES (395, 'Wetzikon (ZH)');
INSERT INTO public.locality (id, name) VALUES (396, 'Saint-Blaise');
INSERT INTO public.locality (id, name) VALUES (397, 'Céligny');
INSERT INTO public.locality (id, name) VALUES (398, 'Pregny-Chambésy');
INSERT INTO public.locality (id, name) VALUES (399, 'Genthod');
INSERT INTO public.locality (id, name) VALUES (400, 'Werthenstein');
INSERT INTO public.locality (id, name) VALUES (401, 'Hasle (LU)');
INSERT INTO public.locality (id, name) VALUES (402, 'Leuggern');
INSERT INTO public.locality (id, name) VALUES (403, 'Mumpf');
INSERT INTO public.locality (id, name) VALUES (404, 'Tirano, Stazione');
INSERT INTO public.locality (id, name) VALUES (405, 'Zihlschlacht-Sitterdorf');
INSERT INTO public.locality (id, name) VALUES (406, 'Klosters');
INSERT INTO public.locality (id, name) VALUES (407, 'Innertkirchen');
INSERT INTO public.locality (id, name) VALUES (408, 'Felben-Wellhausen');
INSERT INTO public.locality (id, name) VALUES (409, 'Belmont-Broye');
INSERT INTO public.locality (id, name) VALUES (410, 'Lugano');
INSERT INTO public.locality (id, name) VALUES (411, 'Emmen');
INSERT INTO public.locality (id, name) VALUES (412, 'Zurzach');
INSERT INTO public.locality (id, name) VALUES (413, 'Capriasca');
INSERT INTO public.locality (id, name) VALUES (414, 'Bulle');
INSERT INTO public.locality (id, name) VALUES (415, 'Erstfeld');
INSERT INTO public.locality (id, name) VALUES (416, 'Echichens');
INSERT INTO public.locality (id, name) VALUES (417, 'Landquart');
INSERT INTO public.locality (id, name) VALUES (418, 'Belfaux');
INSERT INTO public.locality (id, name) VALUES (419, 'Freienbach');
INSERT INTO public.locality (id, name) VALUES (420, 'Finhaut');
INSERT INTO public.locality (id, name) VALUES (421, 'Sevelen');
INSERT INTO public.locality (id, name) VALUES (422, 'Brittnau');
INSERT INTO public.locality (id, name) VALUES (423, 'Sargans');
INSERT INTO public.locality (id, name) VALUES (424, 'Oberrieden');
INSERT INTO public.locality (id, name) VALUES (425, 'Altstätten');
INSERT INTO public.locality (id, name) VALUES (426, 'Stäfa');
INSERT INTO public.locality (id, name) VALUES (427, 'Zizers');
INSERT INTO public.locality (id, name) VALUES (428, 'Lausen');
INSERT INTO public.locality (id, name) VALUES (429, 'Rothrist');
INSERT INTO public.locality (id, name) VALUES (430, 'Dübendorf');
INSERT INTO public.locality (id, name) VALUES (431, 'Genève');
INSERT INTO public.locality (id, name) VALUES (432, 'Schwyz');
INSERT INTO public.locality (id, name) VALUES (433, 'Weggis');
INSERT INTO public.locality (id, name) VALUES (434, 'Vitznau');
INSERT INTO public.locality (id, name) VALUES (435, 'Adliswil');
INSERT INTO public.locality (id, name) VALUES (436, 'Wolhusen');
INSERT INTO public.locality (id, name) VALUES (437, 'Roggwil (TG)');
INSERT INTO public.locality (id, name) VALUES (438, 'Egg');
INSERT INTO public.locality (id, name) VALUES (439, 'Baar');
INSERT INTO public.locality (id, name) VALUES (440, 'Bülach');
INSERT INTO public.locality (id, name) VALUES (441, 'Bellwald');
INSERT INTO public.locality (id, name) VALUES (442, 'Orpund');
INSERT INTO public.locality (id, name) VALUES (443, 'Meinisberg');
INSERT INTO public.locality (id, name) VALUES (444, 'Lotzwil');
INSERT INTO public.locality (id, name) VALUES (445, 'Bözberg');
INSERT INTO public.locality (id, name) VALUES (446, 'Oron');
INSERT INTO public.locality (id, name) VALUES (447, 'Monthey');
INSERT INTO public.locality (id, name) VALUES (448, 'Wangenried');
INSERT INTO public.locality (id, name) VALUES (449, 'Walliswil bei Wangen');
INSERT INTO public.locality (id, name) VALUES (450, 'Aeschi (SO)');
INSERT INTO public.locality (id, name) VALUES (451, 'Ittigen');
INSERT INTO public.locality (id, name) VALUES (452, 'Val-de-Travers');
INSERT INTO public.locality (id, name) VALUES (453, 'Blindleistungskompensator Domo');
INSERT INTO public.locality (id, name) VALUES (454, 'Basse-Allaine');
INSERT INTO public.locality (id, name) VALUES (455, 'Clos du Doubs');
INSERT INTO public.locality (id, name) VALUES (456, 'Orbe');
INSERT INTO public.locality (id, name) VALUES (457, 'Twann-Tüscherz');
INSERT INTO public.locality (id, name) VALUES (458, 'Hitzkirch');
INSERT INTO public.locality (id, name) VALUES (459, 'Vevey');
INSERT INTO public.locality (id, name) VALUES (460, 'Pieterlen');
INSERT INTO public.locality (id, name) VALUES (461, 'Cazis');
INSERT INTO public.locality (id, name) VALUES (462, 'Niederdorf');
INSERT INTO public.locality (id, name) VALUES (463, 'Basel EuroAirport Automat');
INSERT INTO public.locality (id, name) VALUES (464, 'Leymen, Station (F)');
INSERT INTO public.locality (id, name) VALUES (465, 'Chiasso Confine Smistamento');
INSERT INTO public.locality (id, name) VALUES (466, 'Vufflens-la-Ville');
INSERT INTO public.locality (id, name) VALUES (467, 'Thal');
INSERT INTO public.locality (id, name) VALUES (468, 'Steinerberg');
INSERT INTO public.locality (id, name) VALUES (469, 'Liestal');
INSERT INTO public.locality (id, name) VALUES (470, 'Schöftland');
INSERT INTO public.locality (id, name) VALUES (471, 'Sissach');
INSERT INTO public.locality (id, name) VALUES (472, 'Stansstad');
INSERT INTO public.locality (id, name) VALUES (473, 'Val-d''Illiez');
INSERT INTO public.locality (id, name) VALUES (474, 'La Sarraz');
INSERT INTO public.locality (id, name) VALUES (475, 'Malans');
INSERT INTO public.locality (id, name) VALUES (476, 'Bettwiesen');
INSERT INTO public.locality (id, name) VALUES (477, 'Hallwil');
INSERT INTO public.locality (id, name) VALUES (478, 'Rolle');
INSERT INTO public.locality (id, name) VALUES (479, 'Villeneuve (VD)');
INSERT INTO public.locality (id, name) VALUES (480, 'Männedorf');
INSERT INTO public.locality (id, name) VALUES (481, 'Lindau');
INSERT INTO public.locality (id, name) VALUES (482, 'Zumikon');
INSERT INTO public.locality (id, name) VALUES (483, 'Vallorbe');
INSERT INTO public.locality (id, name) VALUES (484, 'Zeihen');
INSERT INTO public.locality (id, name) VALUES (485, 'Seon');
INSERT INTO public.locality (id, name) VALUES (486, 'Fahrwangen');
INSERT INTO public.locality (id, name) VALUES (487, 'La Sagne');
INSERT INTO public.locality (id, name) VALUES (488, 'Hägglingen');
INSERT INTO public.locality (id, name) VALUES (489, 'Wolfenschiessen');
INSERT INTO public.locality (id, name) VALUES (490, 'Hergiswil (NW)');
INSERT INTO public.locality (id, name) VALUES (491, 'Richterswil');
INSERT INTO public.locality (id, name) VALUES (492, 'Giswil');
INSERT INTO public.locality (id, name) VALUES (493, 'Lungern');
INSERT INTO public.locality (id, name) VALUES (494, 'Degersheim');
INSERT INTO public.locality (id, name) VALUES (495, 'Zufikon');
INSERT INTO public.locality (id, name) VALUES (496, 'Gränichen');
INSERT INTO public.locality (id, name) VALUES (497, 'Ramsen');
INSERT INTO public.locality (id, name) VALUES (498, 'Domodossola');
INSERT INTO public.locality (id, name) VALUES (499, 'Mognatta (B)');
INSERT INTO public.locality (id, name) VALUES (500, 'Bäretswil');
INSERT INTO public.locality (id, name) VALUES (501, 'Stallikon');
INSERT INTO public.locality (id, name) VALUES (502, 'Leimbach (AG)');
INSERT INTO public.locality (id, name) VALUES (503, 'Buchs (AG)');
INSERT INTO public.locality (id, name) VALUES (504, 'Bergün Filisur');
INSERT INTO public.locality (id, name) VALUES (505, 'Niederbipp');
INSERT INTO public.locality (id, name) VALUES (506, 'Münchenbuchsee');
INSERT INTO public.locality (id, name) VALUES (507, 'Neuchâtel');
INSERT INTO public.locality (id, name) VALUES (508, 'Iselle Trasporto veicoli');
INSERT INTO public.locality (id, name) VALUES (509, 'Allmendingen');
INSERT INTO public.locality (id, name) VALUES (510, 'Steinach');
INSERT INTO public.locality (id, name) VALUES (511, 'Laupen');
INSERT INTO public.locality (id, name) VALUES (512, 'Sorvilier');
INSERT INTO public.locality (id, name) VALUES (513, 'Thun');
INSERT INTO public.locality (id, name) VALUES (514, 'Grossdietwil');
INSERT INTO public.locality (id, name) VALUES (515, 'Beatenberg');
INSERT INTO public.locality (id, name) VALUES (516, 'Zell (LU)');
INSERT INTO public.locality (id, name) VALUES (517, 'Gams');
INSERT INTO public.locality (id, name) VALUES (518, 'Rüegsau');
INSERT INTO public.locality (id, name) VALUES (519, 'Bellach');
INSERT INTO public.locality (id, name) VALUES (520, 'Eriswil');
INSERT INTO public.locality (id, name) VALUES (521, 'Trachselwald');
INSERT INTO public.locality (id, name) VALUES (522, 'Ipsach');
INSERT INTO public.locality (id, name) VALUES (523, 'Signau');
INSERT INTO public.locality (id, name) VALUES (524, 'Silenen');
INSERT INTO public.locality (id, name) VALUES (525, 'Lenk');
INSERT INTO public.locality (id, name) VALUES (526, 'Wiedlisbach');
INSERT INTO public.locality (id, name) VALUES (527, 'Alchenstorf');
INSERT INTO public.locality (id, name) VALUES (528, 'Interlaken');
INSERT INTO public.locality (id, name) VALUES (529, 'Schönenwerd');
INSERT INTO public.locality (id, name) VALUES (530, 'Dalpe');
INSERT INTO public.locality (id, name) VALUES (531, 'Kernenried');
INSERT INTO public.locality (id, name) VALUES (532, 'Wynau');
INSERT INTO public.locality (id, name) VALUES (533, 'Wünnewil-Flamatt');
INSERT INTO public.locality (id, name) VALUES (534, 'Oberburg');
INSERT INTO public.locality (id, name) VALUES (535, 'Horriwil');
INSERT INTO public.locality (id, name) VALUES (536, 'Kandersteg');
INSERT INTO public.locality (id, name) VALUES (537, 'Altdorf (UR)');
INSERT INTO public.locality (id, name) VALUES (538, 'Bürglen (UR)');
INSERT INTO public.locality (id, name) VALUES (539, 'Biberist');
INSERT INTO public.locality (id, name) VALUES (540, 'Champéry');
INSERT INTO public.locality (id, name) VALUES (541, 'Horw');
INSERT INTO public.locality (id, name) VALUES (542, 'Gersau');
INSERT INTO public.locality (id, name) VALUES (543, 'Bättwil');
INSERT INTO public.locality (id, name) VALUES (544, 'Heiden');
INSERT INTO public.locality (id, name) VALUES (545, 'Minusio');
INSERT INTO public.locality (id, name) VALUES (546, 'Worb');
INSERT INTO public.locality (id, name) VALUES (547, 'Lütisburg');
INSERT INTO public.locality (id, name) VALUES (548, 'Arzier-Le Muids');
INSERT INTO public.locality (id, name) VALUES (549, 'Ringgenberg (BE)');
INSERT INTO public.locality (id, name) VALUES (550, 'Meggen');
INSERT INTO public.locality (id, name) VALUES (551, 'Beckenried');
INSERT INTO public.locality (id, name) VALUES (552, 'Kölliken');
INSERT INTO public.locality (id, name) VALUES (553, 'Courgenay');
INSERT INTO public.locality (id, name) VALUES (554, 'Kreuzlingen Grenze');
INSERT INTO public.locality (id, name) VALUES (555, 'Carouge (GE)');
INSERT INTO public.locality (id, name) VALUES (556, 'Massongex');
INSERT INTO public.locality (id, name) VALUES (557, 'Evionnaz');
INSERT INTO public.locality (id, name) VALUES (558, 'Bad Ragaz');
INSERT INTO public.locality (id, name) VALUES (559, 'Lottstetten West');
INSERT INTO public.locality (id, name) VALUES (560, 'Sennwald');
INSERT INTO public.locality (id, name) VALUES (561, 'Einsiedeln');
INSERT INTO public.locality (id, name) VALUES (562, 'Penthalaz');
INSERT INTO public.locality (id, name) VALUES (563, 'Les Verrières');
INSERT INTO public.locality (id, name) VALUES (564, 'La Plaine-Frontière');
INSERT INTO public.locality (id, name) VALUES (565, 'Meyrin');
INSERT INTO public.locality (id, name) VALUES (566, 'Malters');
INSERT INTO public.locality (id, name) VALUES (567, 'Entlebuch');
INSERT INTO public.locality (id, name) VALUES (568, 'Schüpfheim');
INSERT INTO public.locality (id, name) VALUES (569, 'Satigny');
INSERT INTO public.locality (id, name) VALUES (570, 'Muriaux');
INSERT INTO public.locality (id, name) VALUES (571, 'Gampel-Bratsch');
INSERT INTO public.locality (id, name) VALUES (572, 'Hautemorges');
INSERT INTO public.locality (id, name) VALUES (573, 'Aubonne');
INSERT INTO public.locality (id, name) VALUES (574, 'Amriswil');
INSERT INTO public.locality (id, name) VALUES (575, 'Rochefort');
INSERT INTO public.locality (id, name) VALUES (576, 'Hauptwil-Gottshaus');
INSERT INTO public.locality (id, name) VALUES (577, 'Lully (FR)');
INSERT INTO public.locality (id, name) VALUES (578, 'Reiden');
INSERT INTO public.locality (id, name) VALUES (579, 'Buchs (ZH)');
INSERT INTO public.locality (id, name) VALUES (580, 'Urtenen-Schönbühl');
INSERT INTO public.locality (id, name) VALUES (581, 'Lauperswil');
INSERT INTO public.locality (id, name) VALUES (582, 'Täuffelen');
INSERT INTO public.locality (id, name) VALUES (583, 'Givisiez');
INSERT INTO public.locality (id, name) VALUES (584, 'Agno');
INSERT INTO public.locality (id, name) VALUES (585, 'Ligerz');
INSERT INTO public.locality (id, name) VALUES (586, 'Heimiswil');
INSERT INTO public.locality (id, name) VALUES (587, 'Muntelier');
INSERT INTO public.locality (id, name) VALUES (588, 'Seftigen');
INSERT INTO public.locality (id, name) VALUES (589, 'Schmitten (FR)');
INSERT INTO public.locality (id, name) VALUES (590, 'Kaufdorf');
INSERT INTO public.locality (id, name) VALUES (591, 'Oberdorf (SO)');
INSERT INTO public.locality (id, name) VALUES (592, 'Koppigen');
INSERT INTO public.locality (id, name) VALUES (593, 'Niederried bei Interlaken');
INSERT INTO public.locality (id, name) VALUES (594, 'Wynigen');
INSERT INTO public.locality (id, name) VALUES (595, 'Selzach');
INSERT INTO public.locality (id, name) VALUES (596, 'Langendorf');
INSERT INTO public.locality (id, name) VALUES (597, 'Wyssachen');
INSERT INTO public.locality (id, name) VALUES (598, 'Studen (BE)');
INSERT INTO public.locality (id, name) VALUES (599, 'Balerna');
INSERT INTO public.locality (id, name) VALUES (600, 'Wikon');
INSERT INTO public.locality (id, name) VALUES (601, 'Cheseaux-sur-Lausanne');
INSERT INTO public.locality (id, name) VALUES (602, 'Ependes (VD)');
INSERT INTO public.locality (id, name) VALUES (603, 'Lenzburg');
INSERT INTO public.locality (id, name) VALUES (604, 'Mellikon');
INSERT INTO public.locality (id, name) VALUES (605, 'Les Clées');
INSERT INTO public.locality (id, name) VALUES (606, 'Bubendorf');
INSERT INTO public.locality (id, name) VALUES (607, 'Mammern');
INSERT INTO public.locality (id, name) VALUES (608, 'Glarus');
INSERT INTO public.locality (id, name) VALUES (609, 'Assens');
INSERT INTO public.locality (id, name) VALUES (610, 'Brugg');
INSERT INTO public.locality (id, name) VALUES (611, 'Beringen');
INSERT INTO public.locality (id, name) VALUES (612, 'Wigoltingen');
INSERT INTO public.locality (id, name) VALUES (613, 'Gambarogno');
INSERT INTO public.locality (id, name) VALUES (614, 'Grolley');
INSERT INTO public.locality (id, name) VALUES (615, 'Bioggio');
INSERT INTO public.locality (id, name) VALUES (616, 'Steffisburg');
INSERT INTO public.locality (id, name) VALUES (617, 'Mels');
INSERT INTO public.locality (id, name) VALUES (618, 'Bassersdorf');
INSERT INTO public.locality (id, name) VALUES (619, 'Wettswil am Albis');
INSERT INTO public.locality (id, name) VALUES (620, 'Troistorrents');
INSERT INTO public.locality (id, name) VALUES (621, 'Collombey-Muraz');
INSERT INTO public.locality (id, name) VALUES (622, 'Rüschlikon');
INSERT INTO public.locality (id, name) VALUES (623, 'Seegräben');
INSERT INTO public.locality (id, name) VALUES (624, 'Vernayaz');
INSERT INTO public.locality (id, name) VALUES (625, 'Hundwil');
INSERT INTO public.locality (id, name) VALUES (626, 'Schlieren');
INSERT INTO public.locality (id, name) VALUES (627, 'Dielsdorf');
INSERT INTO public.locality (id, name) VALUES (628, 'Möhlin');
INSERT INTO public.locality (id, name) VALUES (629, 'Rümlang');
INSERT INTO public.locality (id, name) VALUES (630, 'Morschach');
INSERT INTO public.locality (id, name) VALUES (631, 'Eggerberg');
INSERT INTO public.locality (id, name) VALUES (632, 'Oberentfelden');
INSERT INTO public.locality (id, name) VALUES (633, 'Maur');
INSERT INTO public.locality (id, name) VALUES (634, 'Küsnacht (ZH)');
INSERT INTO public.locality (id, name) VALUES (635, 'Saint-Gingolph');
INSERT INTO public.locality (id, name) VALUES (636, 'Safnern');
INSERT INTO public.locality (id, name) VALUES (637, 'Port-Valais');
INSERT INTO public.locality (id, name) VALUES (638, 'Oberwil im Simmental');
INSERT INTO public.locality (id, name) VALUES (639, 'Avry');
INSERT INTO public.locality (id, name) VALUES (640, 'Rumisberg');
INSERT INTO public.locality (id, name) VALUES (641, 'Lohn-Ammannsegg');
INSERT INTO public.locality (id, name) VALUES (642, 'Bettenhausen');
INSERT INTO public.locality (id, name) VALUES (643, 'Grimisuat');
INSERT INTO public.locality (id, name) VALUES (644, 'Rubigen');
INSERT INTO public.locality (id, name) VALUES (645, 'Melchnau');
INSERT INTO public.locality (id, name) VALUES (646, 'Weinfelden');
INSERT INTO public.locality (id, name) VALUES (647, 'Inkwil');
INSERT INTO public.locality (id, name) VALUES (648, 'Haute-Sorne');
INSERT INTO public.locality (id, name) VALUES (649, 'Péry-La Heutte');
INSERT INTO public.locality (id, name) VALUES (650, 'Coppet');
INSERT INTO public.locality (id, name) VALUES (651, 'Val-de-Ruz');
INSERT INTO public.locality (id, name) VALUES (652, 'Creggio');
INSERT INTO public.locality (id, name) VALUES (653, 'Masera');
INSERT INTO public.locality (id, name) VALUES (654, 'Villette (Vigezzo)');
INSERT INTO public.locality (id, name) VALUES (655, 'Trontano');
INSERT INTO public.locality (id, name) VALUES (656, 'Origlio');
INSERT INTO public.locality (id, name) VALUES (657, 'Erlenbach im Simmental');
INSERT INTO public.locality (id, name) VALUES (658, 'Härkingen');
INSERT INTO public.locality (id, name) VALUES (659, 'Appenzell');
INSERT INTO public.locality (id, name) VALUES (660, 'Turgi');
INSERT INTO public.locality (id, name) VALUES (661, 'Bure');
INSERT INTO public.locality (id, name) VALUES (662, 'Lutzenberg');
INSERT INTO public.locality (id, name) VALUES (663, 'Rorschach');
INSERT INTO public.locality (id, name) VALUES (664, 'Buckten');
INSERT INTO public.locality (id, name) VALUES (665, 'Zeglingen');
INSERT INTO public.locality (id, name) VALUES (666, 'Tecknau');
INSERT INTO public.locality (id, name) VALUES (667, 'Frenkendorf');
INSERT INTO public.locality (id, name) VALUES (668, 'Würenlingen');
INSERT INTO public.locality (id, name) VALUES (669, 'Chiasso Olimpino II');
INSERT INTO public.locality (id, name) VALUES (670, 'Uzwil');
INSERT INTO public.locality (id, name) VALUES (671, 'Uetikon am See');
INSERT INTO public.locality (id, name) VALUES (672, 'Stabio (Confine di proprietà)');
INSERT INTO public.locality (id, name) VALUES (673, 'Pfungen');
INSERT INTO public.locality (id, name) VALUES (674, 'Hünenberg');
INSERT INTO public.locality (id, name) VALUES (675, 'Bonstetten');
INSERT INTO public.locality (id, name) VALUES (676, 'Sins');
INSERT INTO public.locality (id, name) VALUES (677, 'Oberkulm');
INSERT INTO public.locality (id, name) VALUES (678, 'Niedergesteln');
INSERT INTO public.locality (id, name) VALUES (679, 'Kradolf-Schönenberg');
INSERT INTO public.locality (id, name) VALUES (680, 'Wilchingen');
INSERT INTO public.locality (id, name) VALUES (681, 'Wiesendangen');
INSERT INTO public.locality (id, name) VALUES (682, 'Montagny (FR)');
INSERT INTO public.locality (id, name) VALUES (683, 'Obergoms');
INSERT INTO public.locality (id, name) VALUES (684, 'Vernier');
INSERT INTO public.locality (id, name) VALUES (685, 'Oberdorf (NW)');
INSERT INTO public.locality (id, name) VALUES (686, 'Echallens');
INSERT INTO public.locality (id, name) VALUES (687, 'Seewis im Prättigau');
INSERT INTO public.locality (id, name) VALUES (688, 'Etagnières');
INSERT INTO public.locality (id, name) VALUES (689, 'Klettgau Landesgrenze');
INSERT INTO public.locality (id, name) VALUES (690, 'Zollikon');
INSERT INTO public.locality (id, name) VALUES (691, 'Rüthi (SG)');
INSERT INTO public.locality (id, name) VALUES (692, 'Grandson');
INSERT INTO public.locality (id, name) VALUES (693, 'Zell (ZH)');
INSERT INTO public.locality (id, name) VALUES (694, 'Eclépens');
INSERT INTO public.locality (id, name) VALUES (695, 'Opfikon');
INSERT INTO public.locality (id, name) VALUES (696, 'Domo II');
INSERT INTO public.locality (id, name) VALUES (697, 'Hirschthal');
INSERT INTO public.locality (id, name) VALUES (698, 'Muolen');
INSERT INTO public.locality (id, name) VALUES (699, 'Langnau am Albis');
INSERT INTO public.locality (id, name) VALUES (700, 'Alpnach');
INSERT INTO public.locality (id, name) VALUES (701, 'Geuensee');
INSERT INTO public.locality (id, name) VALUES (702, 'Rielasingen');
INSERT INTO public.locality (id, name) VALUES (703, 'Waldshut');
INSERT INTO public.locality (id, name) VALUES (704, 'Riehen');
INSERT INTO public.locality (id, name) VALUES (705, 'Maccagno');
INSERT INTO public.locality (id, name) VALUES (706, 'Basel Bad Rbf');
INSERT INTO public.locality (id, name) VALUES (707, 'Lax');
INSERT INTO public.locality (id, name) VALUES (708, 'Wängi');
INSERT INTO public.locality (id, name) VALUES (709, 'Uttigen');
INSERT INTO public.locality (id, name) VALUES (710, 'Prangins');
INSERT INTO public.locality (id, name) VALUES (711, 'Lausanne');
INSERT INTO public.locality (id, name) VALUES (712, 'Vuisternens-devant-Romont');
INSERT INTO public.locality (id, name) VALUES (713, 'Ebikon');
INSERT INTO public.locality (id, name) VALUES (714, 'Chêne-Bougeries');
INSERT INTO public.locality (id, name) VALUES (715, 'Därligen');
INSERT INTO public.locality (id, name) VALUES (716, 'Boltigen');
INSERT INTO public.locality (id, name) VALUES (717, 'Aeschi bei Spiez');
INSERT INTO public.locality (id, name) VALUES (718, 'Bowil');
INSERT INTO public.locality (id, name) VALUES (719, 'Vechigen');
INSERT INTO public.locality (id, name) VALUES (720, 'Lichtensteig');
INSERT INTO public.locality (id, name) VALUES (721, 'Neuenegg');
INSERT INTO public.locality (id, name) VALUES (722, 'Stein am Rhein');
INSERT INTO public.locality (id, name) VALUES (723, 'Reichenburg');
INSERT INTO public.locality (id, name) VALUES (724, 'Altbüron');
INSERT INTO public.locality (id, name) VALUES (725, 'Flims');
INSERT INTO public.locality (id, name) VALUES (726, 'Vezia');
INSERT INTO public.locality (id, name) VALUES (727, 'Lengnau (BE)');
INSERT INTO public.locality (id, name) VALUES (728, 'Trubschachen');
INSERT INTO public.locality (id, name) VALUES (729, 'Sonceboz-Sombeval');
INSERT INTO public.locality (id, name) VALUES (730, 'Oensingen');
INSERT INTO public.locality (id, name) VALUES (731, 'Bettlach');
INSERT INTO public.locality (id, name) VALUES (732, 'Lostorf');
INSERT INTO public.locality (id, name) VALUES (733, 'Tavannes');
INSERT INTO public.locality (id, name) VALUES (734, 'Dürrenroth');
INSERT INTO public.locality (id, name) VALUES (735, 'Witterswil');
INSERT INTO public.locality (id, name) VALUES (736, 'Courtelary');
INSERT INTO public.locality (id, name) VALUES (737, 'Cortébert');
INSERT INTO public.locality (id, name) VALUES (738, 'Lütschental');
INSERT INTO public.locality (id, name) VALUES (739, 'Vaz/Obervaz');
INSERT INTO public.locality (id, name) VALUES (740, 'La Ferrière');
INSERT INTO public.locality (id, name) VALUES (741, 'Martigny-Combe');
INSERT INTO public.locality (id, name) VALUES (742, 'Unterseen');
INSERT INTO public.locality (id, name) VALUES (743, 'Leissigen');
INSERT INTO public.locality (id, name) VALUES (744, 'Vaulruz');
INSERT INTO public.locality (id, name) VALUES (745, 'Muralto');
INSERT INTO public.locality (id, name) VALUES (746, 'Aefligen');
INSERT INTO public.locality (id, name) VALUES (747, 'Châtel-Saint-Denis');
INSERT INTO public.locality (id, name) VALUES (748, 'Bossonnens');
INSERT INTO public.locality (id, name) VALUES (749, 'Niederlenz');
INSERT INTO public.locality (id, name) VALUES (750, 'Meisterschwanden');
INSERT INTO public.locality (id, name) VALUES (751, 'Arnex-sur-Orbe');
INSERT INTO public.locality (id, name) VALUES (752, 'Klingnau');
INSERT INTO public.locality (id, name) VALUES (753, 'Flums');
INSERT INTO public.locality (id, name) VALUES (754, 'Gryon');
INSERT INTO public.locality (id, name) VALUES (755, 'Bursinel');
INSERT INTO public.locality (id, name) VALUES (756, 'Sils im Domleschg');
INSERT INTO public.locality (id, name) VALUES (757, 'Veytaux');
INSERT INTO public.locality (id, name) VALUES (758, 'Münsterlingen');
INSERT INTO public.locality (id, name) VALUES (759, 'Thurnen');
INSERT INTO public.locality (id, name) VALUES (760, 'Siviriez');
INSERT INTO public.locality (id, name) VALUES (761, 'Crans-Montana');
INSERT INTO public.locality (id, name) VALUES (762, 'Tresa');
INSERT INTO public.locality (id, name) VALUES (763, 'Erlen');
INSERT INTO public.locality (id, name) VALUES (764, 'Menziken');
INSERT INTO public.locality (id, name) VALUES (765, 'Val Mara');
INSERT INTO public.locality (id, name) VALUES (766, 'Sion');
INSERT INTO public.locality (id, name) VALUES (767, 'Wagenhausen');
INSERT INTO public.locality (id, name) VALUES (768, 'Bürglen (TG)');
INSERT INTO public.locality (id, name) VALUES (769, 'Lüsslingen-Nennigkofen');
INSERT INTO public.locality (id, name) VALUES (770, 'Madulain');
INSERT INTO public.locality (id, name) VALUES (771, 'Concise');
INSERT INTO public.locality (id, name) VALUES (772, 'Nyon');
INSERT INTO public.locality (id, name) VALUES (773, 'Genolier');
INSERT INTO public.locality (id, name) VALUES (774, 'Bärschwil');
INSERT INTO public.locality (id, name) VALUES (775, 'Medel (Lucmagn)');
INSERT INTO public.locality (id, name) VALUES (776, 'Croy');
INSERT INTO public.locality (id, name) VALUES (777, 'Krattigen');
INSERT INTO public.locality (id, name) VALUES (778, 'Granges-Paccot');
INSERT INTO public.locality (id, name) VALUES (779, 'Matzingen');
INSERT INTO public.locality (id, name) VALUES (780, 'Menznau');
INSERT INTO public.locality (id, name) VALUES (781, 'Dornach');
INSERT INTO public.locality (id, name) VALUES (782, 'Oberbuchsiten');
INSERT INTO public.locality (id, name) VALUES (783, 'Sonvilier');
INSERT INTO public.locality (id, name) VALUES (784, 'Gsteigwiler');
INSERT INTO public.locality (id, name) VALUES (785, 'Hendschiken');
INSERT INTO public.locality (id, name) VALUES (786, 'Villeret');
INSERT INTO public.locality (id, name) VALUES (787, 'Ferden');
INSERT INTO public.locality (id, name) VALUES (788, 'Disentis/Mustér');
INSERT INTO public.locality (id, name) VALUES (789, 'Rossinière');
INSERT INTO public.locality (id, name) VALUES (790, 'Vufflens-le-Château');
INSERT INTO public.locality (id, name) VALUES (791, 'Orsières');
INSERT INTO public.locality (id, name) VALUES (792, 'Celerina/Schlarigna');
INSERT INTO public.locality (id, name) VALUES (793, 'Recherswil');
INSERT INTO public.locality (id, name) VALUES (794, 'Unterkulm');
INSERT INTO public.locality (id, name) VALUES (795, 'Saint-Prex');
INSERT INTO public.locality (id, name) VALUES (796, 'St. Moritz');
INSERT INTO public.locality (id, name) VALUES (797, 'Etoy');
INSERT INTO public.locality (id, name) VALUES (798, 'Jouxtens-Mézery');
INSERT INTO public.locality (id, name) VALUES (799, 'Boniswil');
INSERT INTO public.locality (id, name) VALUES (800, 'Randa');
INSERT INTO public.locality (id, name) VALUES (801, 'Le Grand-Saconnex');
INSERT INTO public.locality (id, name) VALUES (802, 'Berlingen');
INSERT INTO public.locality (id, name) VALUES (803, 'Zuoz');
INSERT INTO public.locality (id, name) VALUES (804, 'Fischenthal');
INSERT INTO public.locality (id, name) VALUES (805, 'Hunzenschwil');
INSERT INTO public.locality (id, name) VALUES (806, 'Dietlikon');
INSERT INTO public.locality (id, name) VALUES (807, 'Henggart');
INSERT INTO public.locality (id, name) VALUES (808, 'Wangen-Brüttisellen');
INSERT INTO public.locality (id, name) VALUES (809, 'Urdorf');
INSERT INTO public.locality (id, name) VALUES (810, 'Rüderswil');
INSERT INTO public.locality (id, name) VALUES (811, 'Grenchen');
INSERT INTO public.locality (id, name) VALUES (812, 'Fräschels');
INSERT INTO public.locality (id, name) VALUES (813, 'Melide');
INSERT INTO public.locality (id, name) VALUES (814, 'Finsterhennen');
INSERT INTO public.locality (id, name) VALUES (815, 'Burgistein');
INSERT INTO public.locality (id, name) VALUES (816, 'Airolo');
INSERT INTO public.locality (id, name) VALUES (817, 'Oberhofen am Thunersee');
INSERT INTO public.locality (id, name) VALUES (818, 'Adelboden');
INSERT INTO public.locality (id, name) VALUES (819, 'Chapelle (Glâne)');
INSERT INTO public.locality (id, name) VALUES (820, 'Hüniken');
INSERT INTO public.locality (id, name) VALUES (821, 'Feldbrunnen-St. Niklaus');
INSERT INTO public.locality (id, name) VALUES (822, 'Aarwangen');
INSERT INTO public.locality (id, name) VALUES (823, 'Müntschemier');
INSERT INTO public.locality (id, name) VALUES (824, 'Siselen');
INSERT INTO public.locality (id, name) VALUES (825, 'Sorengo');
INSERT INTO public.locality (id, name) VALUES (826, 'Caslano');
INSERT INTO public.locality (id, name) VALUES (827, 'Stettlen');
INSERT INTO public.locality (id, name) VALUES (828, 'Grandval');
INSERT INTO public.locality (id, name) VALUES (829, 'Bière');
INSERT INTO public.locality (id, name) VALUES (830, 'Brunegg');
INSERT INTO public.locality (id, name) VALUES (831, 'Romanel-sur-Lausanne');
INSERT INTO public.locality (id, name) VALUES (832, 'Muri (AG)');
INSERT INTO public.locality (id, name) VALUES (833, 'Yens');
INSERT INTO public.locality (id, name) VALUES (834, 'Montagny-près-Yverdon');
INSERT INTO public.locality (id, name) VALUES (835, 'Stans');
INSERT INTO public.locality (id, name) VALUES (836, 'Thusis');
INSERT INTO public.locality (id, name) VALUES (837, 'Münsingen');
INSERT INTO public.locality (id, name) VALUES (838, 'Castel San Pietro');
INSERT INTO public.locality (id, name) VALUES (839, 'Grüsch');
INSERT INTO public.locality (id, name) VALUES (840, 'Villmergen');
INSERT INTO public.locality (id, name) VALUES (841, 'Haut-Intyamon');
INSERT INTO public.locality (id, name) VALUES (842, 'Hüttlingen');
INSERT INTO public.locality (id, name) VALUES (843, 'Fey');
INSERT INTO public.locality (id, name) VALUES (844, 'Schiers');
INSERT INTO public.locality (id, name) VALUES (845, 'Versoix');
INSERT INTO public.locality (id, name) VALUES (846, 'Vendlincourt');
INSERT INTO public.locality (id, name) VALUES (847, 'Massagno');
INSERT INTO public.locality (id, name) VALUES (848, 'Ennetbürgen');
INSERT INTO public.locality (id, name) VALUES (849, 'Seuzach');
INSERT INTO public.locality (id, name) VALUES (850, 'Beinwil am See');
INSERT INTO public.locality (id, name) VALUES (851, 'Kreuzlingen Hafen Grenze');
INSERT INTO public.locality (id, name) VALUES (852, 'Chêne-Bourg-Frontière');
INSERT INTO public.locality (id, name) VALUES (853, 'St-Gingolph (Frontière)');
INSERT INTO public.locality (id, name) VALUES (854, 'Rothenburg');
INSERT INTO public.locality (id, name) VALUES (855, 'Ermensee');
INSERT INTO public.locality (id, name) VALUES (856, 'Neuenkirch');
INSERT INTO public.locality (id, name) VALUES (857, 'Ried-Brig');
INSERT INTO public.locality (id, name) VALUES (858, 'Grellingen');
INSERT INTO public.locality (id, name) VALUES (859, 'Galleria Scigolino Sud');
INSERT INTO public.locality (id, name) VALUES (860, 'Iselle portail tunnel');
INSERT INTO public.locality (id, name) VALUES (861, 'Riddes');
INSERT INTO public.locality (id, name) VALUES (862, 'Uttwil');
INSERT INTO public.locality (id, name) VALUES (863, 'Le Landeron');
INSERT INTO public.locality (id, name) VALUES (864, 'Ruswil');
INSERT INTO public.locality (id, name) VALUES (865, 'Dardagny');
INSERT INTO public.locality (id, name) VALUES (866, 'Rheinfelden');
INSERT INTO public.locality (id, name) VALUES (867, 'Alle');
INSERT INTO public.locality (id, name) VALUES (868, 'Diessenhofen');
INSERT INTO public.locality (id, name) VALUES (869, 'Lengwil');
INSERT INTO public.locality (id, name) VALUES (870, 'Maienfeld');
INSERT INTO public.locality (id, name) VALUES (871, 'Schmitten (GR)');
INSERT INTO public.locality (id, name) VALUES (872, 'Niederhasli');
INSERT INTO public.locality (id, name) VALUES (873, 'Aesch (BL)');
INSERT INTO public.locality (id, name) VALUES (874, 'Dürnten');
INSERT INTO public.locality (id, name) VALUES (875, 'Steinmaur');
INSERT INTO public.locality (id, name) VALUES (876, 'Uitikon');
INSERT INTO public.locality (id, name) VALUES (877, 'Vérossaz');
INSERT INTO public.locality (id, name) VALUES (878, 'Bühler');
INSERT INTO public.locality (id, name) VALUES (879, 'Turtmann-Unterems');
INSERT INTO public.locality (id, name) VALUES (880, 'Andeer');
INSERT INTO public.locality (id, name) VALUES (881, 'Affeltrangen');
INSERT INTO public.locality (id, name) VALUES (882, 'Cadenazzo');
INSERT INTO public.locality (id, name) VALUES (883, 'Marone');
INSERT INTO public.locality (id, name) VALUES (884, 'Coimo');
INSERT INTO public.locality (id, name) VALUES (885, 'Singen (Hohentwiel)');
INSERT INTO public.locality (id, name) VALUES (886, 'Domodossola Aussenkabine');
INSERT INTO public.locality (id, name) VALUES (887, 'Nürensdorf');
INSERT INTO public.locality (id, name) VALUES (888, 'Fieschertal');
INSERT INTO public.locality (id, name) VALUES (889, 'Bercher');
INSERT INTO public.locality (id, name) VALUES (890, 'Domodossola (bif)');
INSERT INTO public.locality (id, name) VALUES (891, 'Konstanz');
INSERT INTO public.locality (id, name) VALUES (892, 'Therwil');
INSERT INTO public.locality (id, name) VALUES (893, 'Holziken');
INSERT INTO public.locality (id, name) VALUES (894, 'Hölstein');
INSERT INTO public.locality (id, name) VALUES (895, 'Rümlingen');
INSERT INTO public.locality (id, name) VALUES (896, 'Oberwil (BL)');
INSERT INTO public.locality (id, name) VALUES (897, 'Rickenbach (LU)');
INSERT INTO public.locality (id, name) VALUES (898, 'Collina d''Oro');
INSERT INTO public.locality (id, name) VALUES (899, 'Bauma');
INSERT INTO public.locality (id, name) VALUES (900, 'Weesen');
INSERT INTO public.locality (id, name) VALUES (901, 'Sachseln');
INSERT INTO public.locality (id, name) VALUES (902, 'Reinach (AG)');
INSERT INTO public.locality (id, name) VALUES (903, 'Büron');
INSERT INTO public.locality (id, name) VALUES (904, 'Waltenschwil');
INSERT INTO public.locality (id, name) VALUES (905, 'Gaggiolo Confine');
INSERT INTO public.locality (id, name) VALUES (906, 'Schinznach');
INSERT INTO public.locality (id, name) VALUES (907, 'Luzein');
INSERT INTO public.locality (id, name) VALUES (908, 'Naters');
INSERT INTO public.locality (id, name) VALUES (909, 'Saas-Fee');
INSERT INTO public.locality (id, name) VALUES (910, 'Walkringen');
INSERT INTO public.locality (id, name) VALUES (911, 'Vionnaz');
INSERT INTO public.locality (id, name) VALUES (912, 'Steckborn');
INSERT INTO public.locality (id, name) VALUES (913, 'La Neuveville');
INSERT INTO public.locality (id, name) VALUES (914, 'Cormoret');
INSERT INTO public.locality (id, name) VALUES (915, 'Paradiso');
INSERT INTO public.locality (id, name) VALUES (916, 'Villars-sur-Glâne');
INSERT INTO public.locality (id, name) VALUES (917, 'Roches (BE)');
INSERT INTO public.locality (id, name) VALUES (918, 'Luterbach');
INSERT INTO public.locality (id, name) VALUES (919, 'Hagneck');
INSERT INTO public.locality (id, name) VALUES (920, 'Bätterkinden');
INSERT INTO public.locality (id, name) VALUES (921, 'Lommiswil');
INSERT INTO public.locality (id, name) VALUES (922, 'Mattstetten');
INSERT INTO public.locality (id, name) VALUES (923, 'Bönigen');
INSERT INTO public.locality (id, name) VALUES (924, 'Zuchwil');
INSERT INTO public.locality (id, name) VALUES (925, 'Hägendorf');
INSERT INTO public.locality (id, name) VALUES (926, 'Füllinsdorf');
INSERT INTO public.locality (id, name) VALUES (927, 'Bottmingen');
INSERT INTO public.locality (id, name) VALUES (928, 'Hemishofen');
INSERT INTO public.locality (id, name) VALUES (929, 'Varzo');
INSERT INTO public.locality (id, name) VALUES (930, 'Küblis');
INSERT INTO public.locality (id, name) VALUES (931, 'Muhen');
INSERT INTO public.locality (id, name) VALUES (932, 'Estavayer');
INSERT INTO public.locality (id, name) VALUES (933, 'Valbirse');
INSERT INTO public.locality (id, name) VALUES (934, 'Moudon');
INSERT INTO public.locality (id, name) VALUES (935, 'Mont-Vully');
INSERT INTO public.locality (id, name) VALUES (936, 'Churwalden');
INSERT INTO public.locality (id, name) VALUES (937, 'Ins');
INSERT INTO public.locality (id, name) VALUES (938, 'Schüpfen');
INSERT INTO public.locality (id, name) VALUES (939, 'Courroux');
INSERT INTO public.locality (id, name) VALUES (940, 'Sils im Engadin/Segl');
INSERT INTO public.locality (id, name) VALUES (941, 'Chénens');
INSERT INTO public.locality (id, name) VALUES (942, 'Giornico');
INSERT INTO public.locality (id, name) VALUES (943, 'Prato (Leventina)');
INSERT INTO public.locality (id, name) VALUES (944, 'Fribourg');
INSERT INTO public.locality (id, name) VALUES (945, 'Lüscherz');
INSERT INTO public.locality (id, name) VALUES (946, 'Magliaso');
INSERT INTO public.locality (id, name) VALUES (947, 'Court');
INSERT INTO public.locality (id, name) VALUES (948, 'Rohrbach');
INSERT INTO public.locality (id, name) VALUES (949, 'Diepflingen');
INSERT INTO public.locality (id, name) VALUES (950, 'Reinach (BL)');
INSERT INTO public.locality (id, name) VALUES (951, 'Arlesheim');
INSERT INTO public.locality (id, name) VALUES (952, 'Dagmersellen');
INSERT INTO public.locality (id, name) VALUES (953, 'Andelfingen');
INSERT INTO public.locality (id, name) VALUES (954, 'Villaz');
INSERT INTO public.locality (id, name) VALUES (955, 'Böztal');
INSERT INTO public.locality (id, name) VALUES (956, 'Laufenburg');
INSERT INTO public.locality (id, name) VALUES (957, 'Schübelbach');
INSERT INTO public.locality (id, name) VALUES (958, 'Sâles');
INSERT INTO public.locality (id, name) VALUES (959, 'Elgg');
INSERT INTO public.locality (id, name) VALUES (960, 'Ostermundigen');
INSERT INTO public.locality (id, name) VALUES (961, 'Hermance');
INSERT INTO public.locality (id, name) VALUES (962, 'Domleschg');
INSERT INTO public.locality (id, name) VALUES (963, 'Val Müstair');
INSERT INTO public.locality (id, name) VALUES (964, 'Rapperswil (BE)');
INSERT INTO public.locality (id, name) VALUES (965, 'Bettmeralp');
INSERT INTO public.locality (id, name) VALUES (966, 'Nebikon');
INSERT INTO public.locality (id, name) VALUES (967, 'Roggliswil');
INSERT INTO public.locality (id, name) VALUES (968, 'Bavois');
INSERT INTO public.locality (id, name) VALUES (969, 'Auenstein');
INSERT INTO public.locality (id, name) VALUES (970, 'Conthey');
INSERT INTO public.locality (id, name) VALUES (971, 'Château-d''Oex');
INSERT INTO public.locality (id, name) VALUES (972, 'Bonvillars');
INSERT INTO public.locality (id, name) VALUES (973, 'Cugy (FR)');
INSERT INTO public.locality (id, name) VALUES (974, 'Stammheim');
INSERT INTO public.locality (id, name) VALUES (975, 'Saint-Cergue');
INSERT INTO public.locality (id, name) VALUES (976, 'Unterbäch');
INSERT INTO public.locality (id, name) VALUES (977, 'Ormont-Dessous');
INSERT INTO public.locality (id, name) VALUES (978, 'Diemtigen');
INSERT INTO public.locality (id, name) VALUES (979, 'Gündlischwand');
INSERT INTO public.locality (id, name) VALUES (980, 'Prilly');
INSERT INTO public.locality (id, name) VALUES (981, 'Güttingen');
INSERT INTO public.locality (id, name) VALUES (982, 'Novazzano');
INSERT INTO public.locality (id, name) VALUES (983, 'Rudolfstetten-Friedlisberg');
INSERT INTO public.locality (id, name) VALUES (984, 'Bubikon');
INSERT INTO public.locality (id, name) VALUES (985, 'S-chanf');
INSERT INTO public.locality (id, name) VALUES (986, 'Bovernier');
INSERT INTO public.locality (id, name) VALUES (987, 'Teufenthal (AG)');
INSERT INTO public.locality (id, name) VALUES (988, 'Altishofen');
INSERT INTO public.locality (id, name) VALUES (989, 'Allaman');
INSERT INTO public.locality (id, name) VALUES (990, 'Unterentfelden');
INSERT INTO public.locality (id, name) VALUES (991, 'Renens (VD)');
INSERT INTO public.locality (id, name) VALUES (992, 'Gland');
INSERT INTO public.locality (id, name) VALUES (993, 'Pompaples');
INSERT INTO public.locality (id, name) VALUES (994, 'Fiesch');
INSERT INTO public.locality (id, name) VALUES (995, 'Wauwil');
INSERT INTO public.locality (id, name) VALUES (996, 'Visperterminen');
INSERT INTO public.locality (id, name) VALUES (997, 'Bretonnières');
INSERT INTO public.locality (id, name) VALUES (998, 'Eysins');
INSERT INTO public.locality (id, name) VALUES (999, 'Wila');
INSERT INTO public.locality (id, name) VALUES (1000, 'Cossonay');
INSERT INTO public.locality (id, name) VALUES (1001, 'Bottighofen');
INSERT INTO public.locality (id, name) VALUES (1002, 'La Punt Chamues-ch');
INSERT INTO public.locality (id, name) VALUES (1003, 'Altnau');
INSERT INTO public.locality (id, name) VALUES (1004, 'Henniez');
INSERT INTO public.locality (id, name) VALUES (1005, 'Birr');
INSERT INTO public.locality (id, name) VALUES (1006, 'Möriken-Wildegg');
INSERT INTO public.locality (id, name) VALUES (1007, 'Gondiswil');
INSERT INTO public.locality (id, name) VALUES (1008, 'Crans (VD)');
INSERT INTO public.locality (id, name) VALUES (1009, 'L''Abbaye');
INSERT INTO public.locality (id, name) VALUES (1010, 'Gontenschwil');
INSERT INTO public.locality (id, name) VALUES (1011, 'Hettlingen');
INSERT INTO public.locality (id, name) VALUES (1012, 'Wangen (SZ)');
INSERT INTO public.locality (id, name) VALUES (1013, 'Samedan');
INSERT INTO public.locality (id, name) VALUES (1014, 'Kaiseraugst');
INSERT INTO public.locality (id, name) VALUES (1015, 'Agarn');
INSERT INTO public.locality (id, name) VALUES (1016, 'Gonten');
INSERT INTO public.locality (id, name) VALUES (1017, 'Folsogno-Dissimo');
INSERT INTO public.locality (id, name) VALUES (1018, 'Trin');
INSERT INTO public.locality (id, name) VALUES (1019, 'Jenaz');
INSERT INTO public.locality (id, name) VALUES (1020, 'Eulach Landesgrenze');
INSERT INTO public.locality (id, name) VALUES (1021, 'Fideris');
INSERT INTO public.locality (id, name) VALUES (1022, 'Biglen');
INSERT INTO public.locality (id, name) VALUES (1023, 'Würenlos');
INSERT INTO public.locality (id, name) VALUES (1024, 'Chêne-Bourg');
INSERT INTO public.locality (id, name) VALUES (1025, 'Courchavon');
INSERT INTO public.locality (id, name) VALUES (1026, 'Zwingen');
INSERT INTO public.locality (id, name) VALUES (1027, 'Liesberg');
INSERT INTO public.locality (id, name) VALUES (1028, 'Au (SG)');
INSERT INTO public.locality (id, name) VALUES (1029, 'Pfäffikon');
INSERT INTO public.locality (id, name) VALUES (1030, 'Cham');
INSERT INTO public.locality (id, name) VALUES (1031, 'Lachen');
INSERT INTO public.locality (id, name) VALUES (1032, 'Haltingen Unterwerk (DB)');
INSERT INTO public.locality (id, name) VALUES (1033, 'Varzo II');
INSERT INTO public.locality (id, name) VALUES (1034, 'Schwerzenbach');
INSERT INTO public.locality (id, name) VALUES (1035, 'Uznach');
INSERT INTO public.locality (id, name) VALUES (1036, 'Salmsach');
INSERT INTO public.locality (id, name) VALUES (1037, 'Trogen');
INSERT INTO public.locality (id, name) VALUES (1038, 'Steinhausen');
INSERT INTO public.locality (id, name) VALUES (1039, 'Soyhières');
INSERT INTO public.locality (id, name) VALUES (1040, 'Riederalp');
INSERT INTO public.locality (id, name) VALUES (1041, 'Surses');
INSERT INTO public.locality (id, name) VALUES (1042, 'Laax');
INSERT INTO public.locality (id, name) VALUES (1043, 'Chexbres');
INSERT INTO public.locality (id, name) VALUES (1044, 'Luins');
INSERT INTO public.locality (id, name) VALUES (1045, 'Läufelfingen');
INSERT INTO public.locality (id, name) VALUES (1046, 'Kerns');
INSERT INTO public.locality (id, name) VALUES (1047, 'Mies');
INSERT INTO public.locality (id, name) VALUES (1048, 'Vuiteboeuf');
INSERT INTO public.locality (id, name) VALUES (1049, 'Thalheim an der Thur');
INSERT INTO public.locality (id, name) VALUES (1050, 'Sursee');
INSERT INTO public.locality (id, name) VALUES (1051, 'Boswil');
INSERT INTO public.locality (id, name) VALUES (1052, 'Märstetten');
INSERT INTO public.locality (id, name) VALUES (1053, 'Wilen (TG)');
INSERT INTO public.locality (id, name) VALUES (1054, 'Nendaz');
INSERT INTO public.locality (id, name) VALUES (1055, 'Stetten (AG)');
INSERT INTO public.locality (id, name) VALUES (1056, 'Luino FFS');
INSERT INTO public.locality (id, name) VALUES (1057, 'Trasadingen');
INSERT INTO public.locality (id, name) VALUES (1058, 'Trélex');
INSERT INTO public.locality (id, name) VALUES (1059, 'Grächen');
INSERT INTO public.locality (id, name) VALUES (1060, 'Courrendlin');
INSERT INTO public.locality (id, name) VALUES (1061, 'Lens');
INSERT INTO public.locality (id, name) VALUES (1062, 'Saint-Maurice');
INSERT INTO public.locality (id, name) VALUES (1063, 'Lupfig');
INSERT INTO public.locality (id, name) VALUES (1064, 'Riedholz');
INSERT INTO public.locality (id, name) VALUES (1065, 'Gretzenbach');
INSERT INTO public.locality (id, name) VALUES (1066, 'Eschlikon');
INSERT INTO public.locality (id, name) VALUES (1067, 'Ecublens (FR)');
INSERT INTO public.locality (id, name) VALUES (1068, 'Sembrancher');
INSERT INTO public.locality (id, name) VALUES (1069, 'Givrins');
INSERT INTO public.locality (id, name) VALUES (1070, 'Dully');
INSERT INTO public.locality (id, name) VALUES (1071, 'Gottlieben');
INSERT INTO public.locality (id, name) VALUES (1072, 'Othmarsingen');
INSERT INTO public.locality (id, name) VALUES (1073, 'Aegerten');
INSERT INTO public.locality (id, name) VALUES (1074, 'Schwaderloch');
INSERT INTO public.locality (id, name) VALUES (1075, 'Tolochenaz');
INSERT INTO public.locality (id, name) VALUES (1076, 'Winznau');
INSERT INTO public.locality (id, name) VALUES (1077, 'Hofstetten bei Brienz');
INSERT INTO public.locality (id, name) VALUES (1078, 'Stabio');
INSERT INTO public.locality (id, name) VALUES (1079, 'Tannay');
INSERT INTO public.locality (id, name) VALUES (1080, 'Faoug');
INSERT INTO public.locality (id, name) VALUES (1081, 'Pino-Tronzano');
INSERT INTO public.locality (id, name) VALUES (1082, 'Niederönz');
INSERT INTO public.locality (id, name) VALUES (1083, 'Rüti bei Büren');
INSERT INTO public.locality (id, name) VALUES (1084, 'Gordola');
INSERT INTO public.locality (id, name) VALUES (1085, 'Le Pâquier (FR)');
INSERT INTO public.locality (id, name) VALUES (1086, 'Reconvilier');
INSERT INTO public.locality (id, name) VALUES (1087, 'Montricher');
INSERT INTO public.locality (id, name) VALUES (1088, 'Yvonand');
INSERT INTO public.locality (id, name) VALUES (1089, 'Niederglatt');
INSERT INTO public.locality (id, name) VALUES (1090, 'Echandens');
INSERT INTO public.locality (id, name) VALUES (1091, 'Salenstein');
INSERT INTO public.locality (id, name) VALUES (1092, 'Mezzovico-Vira');
INSERT INTO public.locality (id, name) VALUES (1093, 'Lamone');
INSERT INTO public.locality (id, name) VALUES (1094, 'Matten bei Interlaken');
INSERT INTO public.locality (id, name) VALUES (1095, 'Brüttelen');
INSERT INTO public.locality (id, name) VALUES (1096, 'Grossaffoltern');
INSERT INTO public.locality (id, name) VALUES (1097, 'Arch');
INSERT INTO public.locality (id, name) VALUES (1098, 'Utzenstorf');
INSERT INTO public.locality (id, name) VALUES (1099, 'Hilterfingen');
INSERT INTO public.locality (id, name) VALUES (1100, 'Leuzigen');
INSERT INTO public.locality (id, name) VALUES (1101, 'Leibstadt');
INSERT INTO public.locality (id, name) VALUES (1102, 'Wittenbach');
INSERT INTO public.locality (id, name) VALUES (1103, 'Perroy');
INSERT INTO public.locality (id, name) VALUES (1104, 'Chigny');
INSERT INTO public.locality (id, name) VALUES (1105, 'Affoltern am Albis');
INSERT INTO public.locality (id, name) VALUES (1106, 'Walenstadt');
INSERT INTO public.locality (id, name) VALUES (1107, 'Semsales');
INSERT INTO public.locality (id, name) VALUES (1108, 'Mettauertal');
INSERT INTO public.locality (id, name) VALUES (1109, 'Bonfol');
INSERT INTO public.locality (id, name) VALUES (1110, 'Bottenwil');
INSERT INTO public.locality (id, name) VALUES (1111, 'Le Bémont (JU)');
INSERT INTO public.locality (id, name) VALUES (1112, 'Flumenthal');
INSERT INTO public.locality (id, name) VALUES (1113, 'Nidau');
INSERT INTO public.locality (id, name) VALUES (1114, 'Gerlafingen');
INSERT INTO public.locality (id, name) VALUES (1115, 'Corcelles (BE)');
INSERT INTO public.locality (id, name) VALUES (1116, 'Toffen');
INSERT INTO public.locality (id, name) VALUES (1117, 'Brenzikofen');
INSERT INTO public.locality (id, name) VALUES (1118, 'Dotzigen');
INSERT INTO public.locality (id, name) VALUES (1119, 'Elsau');
INSERT INTO public.locality (id, name) VALUES (1120, 'Meilen');
INSERT INTO public.locality (id, name) VALUES (1121, 'Birsfelden');
INSERT INTO public.locality (id, name) VALUES (1122, 'Nottwil');
INSERT INTO public.locality (id, name) VALUES (1123, 'Galleria Maccagno Inf. Nord');
INSERT INTO public.locality (id, name) VALUES (1124, 'Cressier (NE)');
INSERT INTO public.locality (id, name) VALUES (1125, 'Russin');
INSERT INTO public.locality (id, name) VALUES (1126, 'Rüti (ZH)');
INSERT INTO public.locality (id, name) VALUES (1127, 'Rheinwald');
INSERT INTO public.locality (id, name) VALUES (1128, 'Bolligen');
INSERT INTO public.locality (id, name) VALUES (1129, 'Riviera');
INSERT INTO public.locality (id, name) VALUES (1130, 'Basadingen-Schlattingen');
INSERT INTO public.locality (id, name) VALUES (1131, 'Ursy');
INSERT INTO public.locality (id, name) VALUES (1132, 'Erlenbach (ZH)');
INSERT INTO public.locality (id, name) VALUES (1133, 'Fehraltorf');
INSERT INTO public.locality (id, name) VALUES (1134, 'Wollerau');
INSERT INTO public.locality (id, name) VALUES (1135, 'Hombrechtikon');
INSERT INTO public.locality (id, name) VALUES (1136, 'Ossingen');
INSERT INTO public.locality (id, name) VALUES (1137, 'Schöfflisdorf');
INSERT INTO public.locality (id, name) VALUES (1138, 'Binningen');
INSERT INTO public.locality (id, name) VALUES (1139, 'Urnäsch');
INSERT INTO public.locality (id, name) VALUES (1140, 'Düdingen');
INSERT INTO public.locality (id, name) VALUES (1141, 'Döttingen');
INSERT INTO public.locality (id, name) VALUES (1142, 'Wettingen');
INSERT INTO public.locality (id, name) VALUES (1143, 'Altenburg-Rheinau');
INSERT INTO public.locality (id, name) VALUES (1144, 'Jestetten');
INSERT INTO public.locality (id, name) VALUES (1145, 'Weiach');
INSERT INTO public.locality (id, name) VALUES (1146, 'Delle-Frontière');
INSERT INTO public.locality (id, name) VALUES (1147, 'Boncourt');
INSERT INTO public.locality (id, name) VALUES (1148, 'Walzenhausen');
INSERT INTO public.locality (id, name) VALUES (1149, 'Oberglatt');
INSERT INTO public.locality (id, name) VALUES (1150, 'Itingen');
INSERT INTO public.locality (id, name) VALUES (1151, 'Kilchberg (ZH)');
INSERT INTO public.locality (id, name) VALUES (1152, 'Chiasso Olimpino I');
INSERT INTO public.locality (id, name) VALUES (1153, 'Benken (SG)');
INSERT INTO public.locality (id, name) VALUES (1154, 'Varzo I');
INSERT INTO public.locality (id, name) VALUES (1155, 'Dachsen');
INSERT INTO public.locality (id, name) VALUES (1156, 'Farnern');
INSERT INTO public.locality (id, name) VALUES (1157, 'Thörigen');
INSERT INTO public.locality (id, name) VALUES (1158, 'Hellsau');
INSERT INTO public.locality (id, name) VALUES (1159, 'Saint-Sulpice (VD)');
INSERT INTO public.locality (id, name) VALUES (1160, 'Valbroye');
INSERT INTO public.locality (id, name) VALUES (1161, 'S. Maria Maggiore');
INSERT INTO public.locality (id, name) VALUES (1162, 'Gagnone-Orcesco');
INSERT INTO public.locality (id, name) VALUES (1163, 'Malesco');
INSERT INTO public.locality (id, name) VALUES (1164, 'Zornasco');
INSERT INTO public.locality (id, name) VALUES (1165, 'Ribellasca');
INSERT INTO public.locality (id, name) VALUES (1166, 'Verigo');
INSERT INTO public.locality (id, name) VALUES (1167, 'Porrentruy');
INSERT INTO public.locality (id, name) VALUES (1168, 'Duggingen');
INSERT INTO public.locality (id, name) VALUES (1169, 'Jonschwil');
INSERT INTO public.locality (id, name) VALUES (1170, 'Schmerikon');
INSERT INTO public.locality (id, name) VALUES (1171, 'Knonau');
INSERT INTO public.locality (id, name) VALUES (1172, 'Saint-Brais');
INSERT INTO public.locality (id, name) VALUES (1173, 'Münchenwiler');
INSERT INTO public.locality (id, name) VALUES (1174, 'Tenero-Contra');
INSERT INTO public.locality (id, name) VALUES (1175, 'Varzo Sottocentrale');
INSERT INTO public.locality (id, name) VALUES (1176, 'Trient');
INSERT INTO public.locality (id, name) VALUES (1177, 'Rhäzüns');
INSERT INTO public.locality (id, name) VALUES (1178, 'Mörigen');
INSERT INTO public.locality (id, name) VALUES (1179, 'Eggersriet');
INSERT INTO public.locality (id, name) VALUES (1180, 'Kiesen');
INSERT INTO public.locality (id, name) VALUES (1181, 'Buochs');
INSERT INTO public.locality (id, name) VALUES (1182, 'Laufen-Uhwiesen');
INSERT INTO public.locality (id, name) VALUES (1183, 'Chiasso Est');
INSERT INTO public.locality (id, name) VALUES (1184, 'Safenwil');
INSERT INTO public.locality (id, name) VALUES (1185, 'Birrwil');
INSERT INTO public.locality (id, name) VALUES (1186, 'Oberkirch');
INSERT INTO public.locality (id, name) VALUES (1187, 'Knutwil');
INSERT INTO public.locality (id, name) VALUES (1188, 'Termen');
INSERT INTO public.locality (id, name) VALUES (1189, 'Ardon');
INSERT INTO public.locality (id, name) VALUES (1190, 'Saxon');
INSERT INTO public.locality (id, name) VALUES (1191, 'Rheinau');
INSERT INTO public.locality (id, name) VALUES (1192, 'Dietwil');
INSERT INTO public.locality (id, name) VALUES (1193, 'Cheyres-Châbles');
INSERT INTO public.locality (id, name) VALUES (1194, 'Oberdiessbach');
INSERT INTO public.locality (id, name) VALUES (1195, 'Thayngen');
INSERT INTO public.locality (id, name) VALUES (1196, 'Untersiggenthal');
INSERT INTO public.locality (id, name) VALUES (1197, 'Leukerbad');
INSERT INTO public.locality (id, name) VALUES (1198, 'Full-Reuenthal');
INSERT INTO public.locality (id, name) VALUES (1199, 'Waldstatt');
INSERT INTO public.locality (id, name) VALUES (1200, 'Champvent');
INSERT INTO public.locality (id, name) VALUES (1201, 'Gruyères');
INSERT INTO public.locality (id, name) VALUES (1202, 'Courtepin');
INSERT INTO public.locality (id, name) VALUES (1203, 'Höchstetten');
INSERT INTO public.locality (id, name) VALUES (1204, 'Schlatt (TG)');
INSERT INTO public.locality (id, name) VALUES (1205, 'Rue');
INSERT INTO public.locality (id, name) VALUES (1206, 'Oberdorf (BL)');
INSERT INTO public.locality (id, name) VALUES (1207, 'Kriens');
INSERT INTO public.locality (id, name) VALUES (1208, 'Druogno');
INSERT INTO public.locality (id, name) VALUES (1209, 'Prestinone');
INSERT INTO public.locality (id, name) VALUES (1210, 'Isella-Olgia');
INSERT INTO public.locality (id, name) VALUES (1211, 'Bret [F]');
INSERT INTO public.locality (id, name) VALUES (1212, 'Wittinsburg');
INSERT INTO public.locality (id, name) VALUES (1213, 'Landesgrenze CH-Liechtenstein');
INSERT INTO public.locality (id, name) VALUES (1214, 'Lucens');
INSERT INTO public.locality (id, name) VALUES (1215, 'Grosshöchstetten');
INSERT INTO public.locality (id, name) VALUES (1216, 'Val de Bagnes');
INSERT INTO public.locality (id, name) VALUES (1217, 'Neuheim');
INSERT INTO public.locality (id, name) VALUES (1218, 'Neunkirch');
INSERT INTO public.locality (id, name) VALUES (1219, 'Eschert');
INSERT INTO public.locality (id, name) VALUES (1220, 'Torricella-Taverne');
INSERT INTO public.locality (id, name) VALUES (1221, 'Onnens (VD)');
INSERT INTO public.locality (id, name) VALUES (1222, 'Yvorne');
INSERT INTO public.locality (id, name) VALUES (1223, 'Hüntwangen');
INSERT INTO public.locality (id, name) VALUES (1224, 'Chamoson');
INSERT INTO public.locality (id, name) VALUES (1225, 'Dinhard');
INSERT INTO public.locality (id, name) VALUES (1226, 'Embrach');
INSERT INTO public.locality (id, name) VALUES (1227, 'Berikon');
INSERT INTO public.locality (id, name) VALUES (1228, 'Preglia');
INSERT INTO public.locality (id, name) VALUES (1229, 'Tirano');
INSERT INTO public.locality (id, name) VALUES (1230, 'Colmegna');
INSERT INTO public.locality (id, name) VALUES (1231, 'Widen');
INSERT INTO public.locality (id, name) VALUES (1232, 'Zetzwil');
INSERT INTO public.locality (id, name) VALUES (1233, 'Iselle di Trasquera');
INSERT INTO public.locality (id, name) VALUES (1234, 'Trey');
INSERT INTO public.locality (id, name) VALUES (1235, 'Remaufens');
INSERT INTO public.locality (id, name) VALUES (1236, 'Erlach');
INSERT INTO public.locality (id, name) VALUES (1237, 'Wilderswil');
INSERT INTO public.locality (id, name) VALUES (1238, 'Brügg');
INSERT INTO public.locality (id, name) VALUES (1239, 'Renan (BE)');
INSERT INTO public.locality (id, name) VALUES (1240, 'Cottens (FR)');
